== Chapter IV.

[.chapter-subtitle--blurb]
1701--1730.

[.chapter-synopsis]
* Passes through part of Scotland into Ireland
* Visits most of the Meetings of Friends in that Nation, and returns.
* Disturbance of a Meeting in the Parish of Canonsby, in Scotland
* Letter on that subject.
* Termination of the Author`'s own Narrative.
* Supplement, briefly noticing his various further Services, his last illness, and his decease

In the year 1701, I had it in my mind to visit Friends in Ireland;
and when the time came I concluded to go,
and having acquainted Friends therewith according to order,
had a certificate from the Monthly Meeting,
and accordingly I took my journey for Ireland, and a Friend of our meeting with me,
whose name was Richard Latimer.
We went through Scotland,
and Gilbert Molleson with some other Friends born in that country,
having sent some Friends`' books relating to the principles of truth,
to be spread abroad in that nation, we dispersed them all along, as we had opportunity,
till we came to Port Patrick, which was about eighty miles;
as the following letter will give a relation.

[.embedded-content-document.letter]
--

[.letter-heading]
From Christopher Story to Gilbert Molleson

[.salutation]
Loving Friend, Gilbert Molleson:

The salutation of dear love reaches to you over sea and land,
whose care (with the rest of your brethren,) has been manifested
in sending to your native country such books as are for information,
concerning those weighty things most certainly believed among us.
I could have desired you might have seen the acceptance
your free gift in the love of God had among them,
but seeing it was not so, I shall give some account as follows.

Another Friend and I, going to visit Friends in Ireland,
and our way being through the west of Scotland,
we looked upon this a fit opportunity to disperse the books in that part of the nation,
and four honest Friends going along with us, we had travelled but a little`" in Scotland,
till we came to a country place where there was a mill, and several people about it.
We passed by, and being gone but a little way, became uneasy,
and not willing to miss the first step, we sent two Friends back again,
with two of the books, who told the people that some of our Friends who lived at London,
being born in the nation of Scotland,
in love to their country had sent those books to be distributed as a free gift;
and we going for Ireland had the distributing of them, desiring them to peruse them,
and let others have the reading of them.
The people with great thankfulness received them;
and almost in every town we gave the like account, and the people were so pleased,
that some offered money, others desired us to drink, but as the books were a free gift,
we would not accept anything on that account.
Near the second hour in the afternoon, we came to Dumfries, and went to an inn,
and after some refreshment we inquired of the innkeeper,
if we might have a room for a meeting, which was refused;
and after we had sat a little together,
we had freedom to go out to the public place in the high street.
When the people saw us walk out, they followed, believing we would have a meeting,
and we sitting down on the Fish-cross, they gathered near us.
I found a concern upon my mind in the love of God,
to exhort them to love and fear the Lord,
as Abraham and others had done in their generation;
I also signified how they manifested it by their faithfulness and obedience to the Lord,
in answering what he required of them.
A great part were very sober and willing to hear, and after some considerable time,
the town officers were sent to disperse the meeting, but they being pretty civil,
were prevailed on to forbear till a Friend had prayed.
And then a Friend gave a relation as aforesaid,
and the people were very desirous to receive the books,
it seeming to be what they wanted, that if we had given many more than we did,
there were persons to receive them with great freedom.

And as we walked in the street, the town officers being with us,
we saw them flocking together to read.
We stayed all night, and walked to and fro in the town,
but no harshness appeared from any; we heard some saying,
"`These are the honest men they disturbed.`"
Next morning we journeyed forward,
and had not gone far till a sober man came down a steep place,
as if he had designed to meet us; after some discourse we gave him a book,
and when he understood what profession we were of,
he greatly desired to converse with us, for that was what he had long wanted, as he said,
and offered to go forward with us, to have some discourse, if we would ride easily;
but after some time we desired him to be satisfied and let us go,
for we hoped the book would give him as full an account of our faith and principles,
as we in a little time could do.
We had frequent opportunities to disperse them to great satisfaction,
and people in receiving them showed us much kindness,
so that our way was very prosperous.

We came to a Friend`'s house that lives at Baldown near Wigton in Galloway,
and no Friends but one being within sixty miles of him, we thought it needful,
he being a man of good repute in the country, to leave a part of the books with him,
desiring him to spread them abroad so that others might peruse them.
We came to Port Patrick, to take shipping for Ireland, and the last night we were there,
having part of the books to dispose of,
your free gift seemed more acceptable to many than if we had given them money;
and having but one left, when upon the sea, near to lose sight of Scotland,
the master of the vessel asked if I would give him a book, I said I had but one,
and he should have it.
There being a calm at that time, they read it from one to another, and I may say,
I had my reward plentifully in the discharge of my duty;
and I hope you will have the like, that they that plough, and they that sow,
may reap together in the time of harvest.

And now being safely arrived in Ireland, the next day was the Province Meeting,
for the north, and we were glad to see Friends generally together.
With my dear love once more to you and faithful Friends,
as also to Friends that come from Cumberland to the Yearly Meeting, I bid you farewell.

[.signed-section-closing]
From your Friend,

[.signed-section-signature]
Christopher Story

[.signed-section-context-close]
Lurgan, in Ireland, the 21st of the 3d month, 1701.

--

At the Province Meeting, which was both a large and good meeting,
accounts were brought in from the particular meetings,
of the care and faithfulness of Friends, in various branches of our testimony,
except in one place, where some relations had paid tithes,
or something in lieu of tithes, for Friends, and this became an exercise to the meeting,
for it spread about like a leprosy, and was an evil example to others.
Some would argue, that Friends`' relations would not be prevailed with not to meddle;
but as honest endeavours were used, this practice was set aside,
as it has been in several places, to my knowledge,
where Friends were truly careful to come up with their faithful
brethren in this weighty branch of our testimony.
I have also for many years observed, that where Friends were lukewarm,
and not faithful in this testimony, they did not prosper in the truth,
but rather decayed and withered.

After we had visited meetings in that Province, we travelled towards the Moat;
and at Mountmellick, were at the Province Meeting, to good satisfaction;
so proceeded to Limerick, and Cork, and were at their Province meeting at Clonmel.
I was glad to see Friends so established in the truth,
there being a great reformation in various parts, since the time I had been there before,
which was about fourteen years.
We went to the Province meeting at Wicklow, and having seen Friends pretty generally,
been at four Province meetings,
and in about twelve weeks visited most of the meetings in Ireland,
after we had stayed some time in Dublin, we came for Cumberland;
and meeting with no contrary winds at sea, came readily home to our families,
with desires to the Lord that we may be thankful for all his mercies.

And now, by the good providence of God,
being eased of various troubles which but a few years before we lay under,
we began to think of our neighbors that lived at Canonsby,
who had been so cruel against us when we met at Tarras-side, as before related.
Having liberty granted to keep a meeting at Woodhouse-Lees, in the same parish,
when Friends were met and sat down, to keep our meeting abroad,
there being no house convenient to contain the multitude,
bailiff Melvin with a company of men on horseback, and others on foot,
brought out of several parishes, some of them of the baser sort,
came on purpose to disturb our meeting: we being sat down on the ground,
if the said Melvin had not taken special care,
in all appearance they would have trodden Friends with their horses`' feet.
They commanded us to be gone;
yet we were not free to depart until the meeting time was over;
and therefore they began to throw Friends down a steep place, on purpose to disperse us,
and did it with such fierceness and violence,
that sometimes they tumbled down themselves with Friends; but the ground being dry,
Friends came up again, and they heated and fatigued themselves so much,
that after some time they grew weary.
And several public Friends being there, as they began to speak,
they hurried them into a wood that was near, and the people followed,
and Friends sounded the testimony of truth among them,
and the well-inclined were willing to hear.
Henry Atkinson offering to pray, two men on horseback took him away,
and dragged him through the river, where the ford was deep,
and put him into a house on the other side- When Friends had freedom, we parted,
and through the Lord`'s mercy, there was no Friend that received any great damage.
Believing that J. Armstrong, priest of Canonsby, with others of his brethren,
were the cause of this great abuse we received,
I had it in my mind to write a letter to the said priest,
which was delivered into his hand by two Friends, and is as follows:

[.embedded-content-document.letter]
--

[.letter-heading]
Christopher Story to James Armstrong

[.salutation]
To James Armstrong, priest of Canonsby, and the rest of his brethren.

Upon the 4th of the sixth month last,
we had it upon our minds in the love of God to visit you our neighbors in Canonsby parish,
and thereabouts; and though we have lived for many years not many miles distant,
yet we suppose are not so well known to you as we desire to be,
in the most weighty matters relating to salvation.
When we were come together to wait upon the Lord,
and to perform that worship which is in spirit and in truth, John Melvin,
with many others, several of whom seemed to be of the baser sort,
in a rude unchristian manner, disturbed us.
I being there, had something upon my mind to speak to the people,
showing in what manner we expected to be saved, desiring their audience;
but without giving me liberty, they haled me away,
as they had done my brethren before me;
and not having opportunity to speak in the hearing of all,
what was at that time upon my mind, I shall here give you and your brethren some account,
that you may judge.
It was as followeth:

That there is no other name given under heaven by which men can be saved,
but by the name of Jesus, unto whose name every knee must bow, and tongue confess,
either in judgment or in mercy:
and that it was the same Jesus Christ who was born of the Virgin Mary,
in Bethlehem of Judea, whose life Herod sought, who after he had wrought many miracles,
suffered the contradiction of sinners,
and his precious blood was shed without the gates of Jerusalem.
He tasted death for mankind,
that he might be a propitiation for the sins of the whole world;
was laid in the new sepulchre, rose again the third day,
and after his appearing unto his disciples, as the Scripture makes mention,
was received into a cloud out of their sight, and sits at the right hand of the Father.
All which testimonies recorded in the Scriptures of truth,
from the time of the Virgin Mary`'s being overshadowed by the Holy Spirit,
and the child Jesus being brought forth in Bethlehem of Judea,
unto that day when the cloud received him out of the disciples`' sight,
all Christians that ever I met with agree in; and we are of the same belief.

And this being part of what was upon my mind at that time,
another thing that followed was, that after Christ Jesus ascended up on high,
he gave gifts unto men, some apostles, some prophets, some evangelists, etc.
(Read the fourth chapter of the Ephesians) "`Till we all come in the unity of the faith,
and of the knowledge of the Son of God, unto a perfect man,
unto the measure of the stature of the fulness of Christ.`"
And the same apostle writing to the Corinthians in chapter twelfth,
concerning the diversities of gifts, but the same spirit; says,
that a "`Manifestation of the spirit is given to every man to profit withal;`"
and this makes good the words of our Lord and Savior to his disciples,
John xvi.
"`Nevertheless I tell you the truth; it is expedient for you that I go away;
for if I go not away, the Comforter will not come unto you: but if I depart,
I will send him unto you.
And when he is come, he will reprove the world of sin, and of righteousness,
and of judgment, and will guide you into all truth.`"
And seeing that which is to be known of God is manifested in man,
for God has showed it unto them, as in Rom. 1,
it is our message to you and all people wherever we come or go,
to direct all to the Spirit of truth that convinces of sin and leads into all truth.
And this is the word nigh "`even in your mouth and in your heart,`" Rom. 10,
which the apostle preached,
and that every one that has an ear might hear what the spirit says, is no new doctrine,
"`for as many as are led by the spirit of God, they are the sons of God;`" Rom. 8:14.
Why we should be reviled and abused for exhorting people that have believed in God,
and in Christ Jesus, to be led by the Holy Spirit of God,
that thereby they may work out their own salvation with fear and trembling, you judge.
Though we have been unchristianly treated by you, yet we do suppose you know us not,
and therefore we can pray and say in reality, "`Lord, forgive them,
for they know not what they do;`" for all that have
persecuted God`'s people in every age,
such was their blindness and hardness of heart, that they knew them not,
as they were really concerned on the Lord`'s account.

It would be too tedious to go back to the days of the patriarchs and prophets,
and speak of the blindness of the Sodomites, and the hard-heartedness of the Jews,
mentioned in the lamentation of our Lord and Savior over Jerusalem;
who killed the prophets, and stoned them that were sent unto them,
until the day of their visitation was over,
and the things belonging to their peace were hid from them.
When our Lord and Savior appeared in the prepared body to do the will of his Father,
as the prophets had prophesied of him;
though he wrought the works which no other could do,
yet how few were there that believed in him.
Neither did many of the learned Jews,
nor wise Scribes and Pharisees know him as he was the Lord of life and glory,
otherwise they would not have crucified him, and put him to open shame.
Neither did they know holy Stephen whom they ran upon, and stoned to death;
neither did Paul while he was Saul, though brought up at the feet of Gamaliel,
and exceeding many in learning and zeal, know the believers in Christ Jesus,
but had his commission from the high priests to bring them bound to Jerusalem;
and persecuted the true church with great severity,
until the Lord appeared unto him by the way, saying, "`Saul, Saul,
why do you persecute me?`"
And such was his ignorance when fear fell upon him, that he cried, "`Lord! who are you?`"
Not to speak particularly of the persecutions under the Roman emperors,
who knew not the Lord`'s people as they were truly his,
and so persecuted them as deluded and heretics;
but to come to the martyrs`' day and time,
who were persecuted by such as professed Christianity,
under the name of being guilty of heresy and delusion,
which they were never able to prove, and yet used all manner of severity against them,
which plainly shows they knew them not as they were the Lord`'s witnesses upon earth,
and counted worthy not only to believe, but also to suffer for his name`'s sake.
And to come a little nearer also, to the professors in New England,
which is scarcely an age past, who used such severity to our Friends there,
that they hanged three men and a woman, and others they whipped, and beat severely,
and some had their ears cut off,
whereas nothing was ever proved against them by the testimony of the Holy Scripture,
that will render them unsound either in faith or practice;
all which severity shows those professors in New
England to be of the same spirit that crucified Christ,
stoned Stephen, and murdered the martyrs.

And though a cloud of witnesses may be brought out
of the Holy Scriptures and church histories,
to prove that it was the birth born after the flesh
that persecuted the birth born after the spirit;
yet where do we read in the Gospel dispensation, that the true church, the bride,
the Lamb`'s wife, used violence to any people as you have done to us these two times.
And though this last time they were not so severe as before in beating us;
yet the like severity in throwing an innocent people over a brow,
as though they had been casting sheep into a water, not regarding old or young,
without any just occasion, has not been often known.
One in performing a religious duty, which is, to pray everywhere,
lifting up holy hands unto God, was violently pulled off his knees,
and dragged through the river where the ford was deepest;
and among those who were severe, there was your man the clerk, and schoolmaster,
(as people said,) which, if so, shows no good government in your family.

Now seeing it has been the advice of good men not to judge others before they hear them,
all that we desire of you is, to search us thoroughly both by word and writing;
and I do not doubt but when you come to know us as we are, you will be made to say,
as some of your brethren have been, who never came to be of our Society,
"`You are not such people as you are represented to be.`"

A few lines from you is desired,
hoping you will be charitable for the future concerning us.
To love enemies is an incumbent duty; and here we desire to remain.

[.signed-section-closing]
By a lover of truth and righteousness,

[.signed-section-signature]
Christopher Story

--

The 26th of the sixth month, 1701, the foregoing paper was read publicly among them,
in the hearing of many, as I am informed, and after several consultations about it,
at last they concluded, that to answer by silence would be best.

Some time after, we had a meeting at the same place, and no disturbance;
they used their endeavours privately to persuade the people not to come to the meeting,
but as to words or writing were pretty quiet.

[.small-break]
'''

[.centered]
The End of the Author`'s Narrative.
