== Supplement.

Having carefully collected the foregoing sheets out
of the papers of this our worthy Friend;
and no farther account appearing among them of anything
particularly relating to himself for many years together,
it is demonstration to us,
that his concern has been rather to leave to succeeding times the
way and manner truth first broke in upon this barren country,
(which at that time was like a wilderness as to the knowledge
of God,) than to give a journal of his own services therein.
These were not a few in the church in his day there being many remaining witnesses of
his diligence and application in encouraging and confirming the churches in this country,
where his service was truly great, and among whom he was honorably esteemed,
being as a tender father and a faithful watchman over the flock of Christ,
that nothing might get in among or prevail over them that would prove hurtful,
and hinder the work of regeneration.

The Lord having favored him with a good understanding
and peculiar talent in the Discipline of the church,
he was careful and very diligent to exercise the same, to the comfort of God`'s people;
and his labor among them in much plainness and sincerity,
being very tender over the weak, but zealous against the willful and stubborn,
to whom he was often terror.

As he was favored also with a good understanding in temporal affairs,
in moral and civil rights, he was often employed in that good work of ending differences,
and putting a period to strife among his neighbors of other communities,
with great success; often satisfying both parties.

Although he has given but little account of his services abroad in this collection,
yet he often visited the churches in several parts of this nation,
as likewise in Ireland and Scotland, as is well remembered by many;
and being frequently at the Yearly Meetings at London, attending the service there,
he commonly spent much time in visiting Friends in several counties on such occasions,
in his going up and returning.

In the latter part of his time,
it became much his concern to appoint meetings in fresh places,
in which he was often very serviceable, his testimony being not only living and powerful,
but plain, pertinent, and well adapted to various states,
much tending to the opening of the understandings
of people in things relating to the kingdom of Christ,
as well in principle and doctrine, as practice.
His behavior and conduct at all times, was in such mildness and gravity,
that it greatly adorned and confirmed his testimony; so that we have reason to believe,
his labor of love had good effects.
But as the Lord, in all ages of the world, has ever called home his faithful servants,
in the fulness of his own time, to reward them with peaceful and glorious habitations,
it pleased him to visit this our dear Friend with a lingering
sickness about the seventy-second year of his age,
which gradually wasted his natural strength; during all which time,
he nevertheless diligently attended the meeting to which he belonged.
And though his outward man decayed, yet his inner man was strong in the Lord,
as appeared by the many living and comforting testimonies
he bore during his bodily weakness.
In the time of his illness many excellent things dropped from his lips,
on several occasions,
and he was surely one of those (as appeared from his own
mouth) whose hope is in the Lord in the time of his death,
which happened at his own house at Righead, on the 6th of the eleventh month, 1720.

His body was interred in our burying-place adjacent, on the 8th of the same;
on which occasion a large congregation of Friends and others assembled,
where the Lord was pleased to engage some of his servants
in living testimonies to his truth and way of life,
and salvation by Christ our Savior; through whom to God the Father of all,
be attributed and ascribed all dominion and praise, as alone worthy now and forever.

Robert Latimer.

Several letters of Christopher Story to his wife;
written in his absence from home on Truth`'s service.

Edinburgh, the 13th of the 10th month, 1680.

Dear Wife,

My love in that which is unchangeable is unto you and my dear children,
with a true desire for your preservation and well-being every way,
but especially in the blessed truth of our God,
for we are made sensible that all things that can be enjoyed appertaining to this life,
will vanish and come to an end; but to know a well-being in the Lord,
who is without beginning of days, or end of years,
whose kingdom is from everlasting to everlasting, is precious;
and blessed and happy are all they who have received
the promise and earnest of this inheritance,
in their own hearts.
They have more cause to rejoice and be exceeding glad,
than they that enjoy the increase of corn, wine, and oil, or anything that is visible.

Having through well-doing and obedience to your Maker, received in your measure,
the earnest and promise of everlasting life if you abide faithful, O! continue faithful,
for the Lord who has promised, will certainly perform,
for his promises are all yes and amen forever,
unto all that walk before him with an upright heart.
Let your care and concern be to serve the Lord with all your heart,
and let him have the chief room there, that so the Lord may delight to abide with you;
that through the daily enjoyment of his presence, you may have cause to rejoice,
and by living experience say, "`In his presence there is fulness of joy,
and at his right hand there are pleasures forevermore.`"

At present I am well every way, blessed be the Lord.
I have had a prosperous journey hitherto; and for aught I know, am clear of the west;
I have seen Friends for the most part, and I could not pass by four Friends in the west,
which was near forty miles out of my way, and was well refreshed to see them,
and I had the company of two good Friends, namely, Hugh Wood and John Hart.
At this meeting last first-day, where were many good Friends, we had a comfortable time;
and truly, I can say to the praise of the Lord, as I am diligent in waiting upon him,
the Lord is near me to my comfort and encouragement, blessed be his name forever.
I am intending, if the Lord enable me with health and liberty,
to go for the north shortly.
My love once more to you, my father and mother, and to my children,
and friends and relations, as though named,
hoping that all the honest-hearted are sensible of my love, as I am of^ theirs;
in remembrance of which love, my heart has been broken,
and my spirit bowed before the Lord many times which
love I pray God may increase and grow among us.

And now, dear wife, let your care be great over my children; and tell them,
as they will answer me, that they be obedient to you, their mother, in all things.
And let my son Richard know, that I desire him not to go abroad in the night time,
but keep at home, and be obedient to you, and loving,
and a good example to the rest of the children;
and if it please God that I may return in safety,
it will be my care to reward according to their doings.

This being the most at present from your ever loving husband,

Christopher Story.

[.asterism]
'''

Bristol, the 30th of the 9th month, 1689.

Dear and loving Wife,

In that love and life which is stronger than death,
where the souls of a remnant ascend over all unto God,
delighting themselves in his presence, do I very dearly salute you,
and recommend you unto the Lord, in whom our life and breathing is,
whose presence is everywhere, and always ready to do good unto his,
that truly and sincerely love and wait upon him.
I know unto such his mercies are as the dew, and his kindness as the small rain,
watering every plantation that is his, that through all that is here below,
the mind may be centred and wholly gathered into the weighty Seed,
which is sufficient to preserve us all unto the kingdom of rest and peace with the Lord,
where all the holy ancients inhabit.
And now the day being come, wherein the Lord is betrothing many unto himself,
may we partake of this glory and holy habitation;
in beholding which many are made to bow down in spirit, and say.
Worthy, worthy are you, O God, who live forever, to rule, and reign,
and have dominion in the hearts of your children, for the Lamb that was slain is alive,
and we live by him.
Because of this, my soul rejoices at this time,
and makes me say with reverence and holy fear.
Glory to God on high, and to the Lamb who lives forever.

And dear wife, press daily to gather our children unto a sense of this;
and I entreat you watch over them for good, that the Lord our God, who has blessed us,
may bless our children.
And though I am separated for a time, I am not unmindful of you in my prayers;
neither am I doubtful,
but the Lord will bless every one with a portion of his spirit as they are faithful.
Give the remembrance of my dear love to my father and mother,
and to all my dear children, whom I pray God he may bless.
Your care concerning me I know will be great; but by this know I am very well every way,
for which I bless the Lord.
We are now at Bristol, and we purpose to go to London,
to be there about the time called Christmas; I desire to hear from you.
We have had a sweet passage and things have been well upon our account,
It is our duty to give the Lord the praise, who is the filler of our cups;
to whom be honor and glory now and forever, Amen.

Give the remembrance of my love to my dear brother Christopher Taylor, Andrew Graham,
both the William Grahams and their wives; and all other my faithful friends,
and to my neigh hours and relations, as though named, who desire to hear from me;
not forgetting once more my duty to my father and mother, love to yourself,
and all our dear children.

The Lord be with you all, says my soul, Amen.

Christopher Story.

[.asterism]
'''

Newcastle, the 11th of the 9th month, 1692.

Dear and loving Wife,

This comes to acquaint you, I am very well, blessed be the Lord;
and have had a peaceable journey to my great satisfaction and comfort, and I can say,
though alone, I have not wearied, for Friends`' love has been such,
that after the first day`'s journey, I have not often lacked company,
beyond my expectation.

I had a drawing in my mind to Glasgow, to be there the first-day after I went from home,
and pressing forward, visited Friends by the way;
when I came there I met with Andrew Jaffray and John Hall of Aberdeen.
We had the greatest meeting of Friends, that we have heard has been in that place,
and had it peaceable, to our comfort, till near the conclusion,
and then one of the magistrates with other officers, dispersed us,
but they offered little abuse, only mocked and scoffed us;
but it being the first-day would not stone us.
We stayed in Glasgow all night, and without any disturbance left the town,
and several Friends being in company, took meetings by the way,
till we came to Edinburgh, to their Quarterly Meeting,
where we had some precious meetings to our great comfort;
several Friends being there from various parts of the nation.
I remained in Edinburgh till the first-day was over, so set forward,
visiting Friends`' meeting at Kelso and Otterburn, and yesternight came here.
I intend to visit most of the meetings in Bishopric,
am likely to come through some of the Dales in Yorkshire, and so to Westmoreland.

Dear wife, I would not have you be any otherwise concerned for me,
than that our only delight may be in the Lord, for it is here the righteous are gathered,
knowing assuredly that all other joys and comforts will fade away as in a moment.
Therefore let us be joined to the Lord, in the one spirit,
where the aboundings of love are known,
and the refreshing streams of his kindness are plentifully drunk of:
for though wife may be near unto husband, and husband near unto wife,
yet the Lord is all in all to his people; he is known to be more than all to a remnant.
It is in the Lord only, that we can rightly enjoy one another,
and bless his name when we are together, and when we are separated one from another;
for the Lord is opening the understandings of his people,
to see that they that marry are to be as though they married not, and they that possess,
as though they possessed not.
He is at work in the hearts of his people,
to wean them from having their chief delight in that which is fading and visible,
and to set it on that which is invisible, where the just shine as the firmament,
and the faithful are as the angels of God, married to the Lamb, forever and ever.
All that are rightly come to the dawning of this day in their own particulars,
+++[+++are arrived]
where a taste of this glory is enjoyed, which will make all the upright in heart say.
One day with the Lord, is as a thousand years, and a thousand years as one day.
It is the sense of these things,
which as unspeakable joys are set before the eyes of the faithful,
makes many deny themselves of the enjoyment of other things which may be dear unto them,
and as the apple of their eye.
Therefore the mark being before, O that we may ever keep here,
where we are more and more sensible of the glorious presence of the Lord,
to shine upon our tabernacles, then shall we witness the morning stars to sing together,
and the sons of God to shout for joy.
Here the smiles of his countenance are known, where many are saying in their hearts,
"`I am my beloved`'s and my beloved is mine.`"
It is here the Lord has brought and is bringing his lambs to rest,
where he is feeding his flocks in the pleasant valleys, beside the still waters,
where the voice of the turtle is heard,
and the rose of Sharon blossoms and casts a sweet smell.

The Lord preserve you, my dear wife, with all my dear children here,
then will you be an honor to the Lord, and a joy and comfort one unto another;
so shall your peace spring as a river, and your righteousness be as the waves of the sea.
It is my daily travail, that Zion may arise and shine in her ancient beauty,
and Jerusalem may be the praise of the whole earth,
and that the knowledge of the Lord may cover the earth as the waters cover the seas,
that God over all may be exalted, who is worthy, now and forever.
I am in great haste,
but desire to have my very dear love remembered to my father and mother,
and all my dear children as if named, and love to all Friends that may inquire after me.
I rest your ever loving husband,

Christopher Story.

The End.
