[quote.epigraph, , Prov. 4:18]
____
The path of the just is as the shining light,
that shines more and more unto the perfect day.
____

[quote.epigraph, , Ps. 37:37]
____
Mark the perfect man, and behold the upright; for the end of that man is peace.
____

== Chapter I

[.chapter-synopsis]
* Birth
* Education
* Early Conviction
* Marriage
* Becomes convinced of the Principles of Friends
* A meeting settled
* Meetings generally held in silence
* Many convinced
* Call to the Ministry
* Visit to Scotland

I was born at Righead, in the parish of Kirklinton, in Cumberland,
about six miles from Carlisle, and nearly as much from Scotland,
in the beginning of the fourth month, 1648.
My father`'s name was Thomas Story, a younger brother of the family of the Story`'s,
who lived at Lake, in that parish.
My mother`'s name was Elizabeth Parret, eldest daughter of Christopher Parret,
who had been priest of the same parish, and being an industrious man,
he bought that estate of land, which I now possess, and improved it to a good degree.
Being the only son my father and mother had, who lived to grow up,
they began betimes to give me education, and I gained favor of most that knew me.

My father, having been servant to Philip Musgrave, of Edenhall, knight,
(of an ancient family in the county of Cumberland,) who
in the time of the civil war between the king and parliament,
was for the king, underwent many jeopardies, to the hazard of his life.
But when King Charles II. was restored to the crown,
the said Philip Musgrave being in favor with him,
had great places of profit and trust under government;
and then he rewarded my father for his former services.
Being sometimes with my father, when he went to see him;
he ordered him to send me to his house, at such times in the year as he thought best,
to learn breeding and good manners, as they call it.
At one time he said to my father, he had a son to send to the university,
about my age and if he would fit me with learning suitable for that place,
he would send me thither with his son and bear my charge.

I was kept at school until the time I was to have gone to the university,
but when it came, my mother was not willing, and her reason was this,
"`If I should be educated at the college,
it was doubtful whether I ever came to live in the country; and it might happen,
that I would sell the land, and live elsewhere;
and considering that I was likely to have sufficient to live upon,
she would not consent I should go.`"

And I may say, that God, who created man in his own image, for a purpose of his glory,
hath regard unto him and to his future happiness;
as appears by his patience and long-suffering, which hath led many to repentance:
notwithstanding their former disobedience and rebellion
against his law written in their hearts,
and his good spirit that he hath put in their inward parts.

Amongst the many thousands of the disobedient and rebellious,
unto whom the Lord in his love and unspeakable kindness, extended mercy,
in and through his dear Son, Christ Jesus,
I was one whom the Lord called by his grace when I was young in years,
and preserved me from many evils, to which I was prone as well as others.
I scarcely knew it was the Lord,
but felt there was something near me and with me from a child,
that inclined my heart to seek after the Lord, and to read the Holy Scriptures.
As I grew up to years of understanding, I was sober and more moderate than some others,
though the place of my abode was in the border of England,
where wickedness of the grossest sort had swelled to that height, that theft,
robbery and bloodshed, with many other crying sins, were so very frequent,
that hell (in that sense) had opened her mouth; the remembrance of which,
much affects my heart with sorrow.
When I think of such as are gone, who were but an age before me,
and several others that are largely made partakers of the mercy of God;
that the Lord in his free love, should pluck us as brands out of the fire,
and preserve us from those gross evils, which generations before us were found in,
I feel is an obligation never to be forgotten.

As the Lord was pleased to get himself a name in the earth,
in calling us to be a people to his praise, who were as the outcasts of the nation,
he began to work in the hearts of a young generation, when but tender in age,
of which I was one: and though we were short of having an eye unto the Lord,
in all our undertakings, yet He was not short in having an eye over us for good.
I was brought up in a public-house,
my father and mother keeping an inn where people of many sorts resorted,
yet the Lord preserved me beyond many from the sin of drunkenness,
and the excessive smoking of tobacco I never loved.

Yet as I grew in years, I was drawn after the vain pastimes which are in the world;
as shooting with guns and bows, and following them that played at cards,
and I was successful in playing, and my mind as much taken with that foolish practice,
as most things.
For this the Lord gave me a sore rebuke in myself,
that I was sensible of trouble of conscience for many days,
and was consulting with myself, what to do,
not knowing of one man who judged the thing unlawful to be done.
The old enemy appeared in my heart and brought a fair pretense with him, viz:
that I might safely play at any time except the first-days at night,
being a practice amongst us; and this gave me a little ease for a time;
and I observed it.
Then a fear entered my mind, that I durst not join with young people in their pastimes,
and light began more to appear, and I saw we must be more religious than formerly;
but the enemy would suggest to me that I was young, and might live long,
and it was time enough for me to be religious when I was married;
and here I rested for some years, though often under trouble,
believing I must live more godly, or otherwise I could not enter God`'s kingdom.

When I was about eighteen years of age,
my father and mother were desirous I should marry a young
woman whose parents were of good repute in the country;
and a weighty concern it was to me, and under the sense thereof,
I prayed to the Lord in the night season, "`that if it were for our good,
it might come to pass, and if not, it might not be so.`"
About this time, my heart came to be more and more opened,
and I saw the danger of poverty and riches, and at a certain time, I retired,
and the saying of the wise man came into my remembrance,
and I prayed to the Lord to give me neither poverty nor riches,
for I saw there was danger on both hands;
and though I desired to keep company with those that were most sober,
yet was I often under great affliction of mind.

When I was at any time with the profane, if I partook of their joy at night,
sorrow came in the morning.
While I remained here, a great fever being in the country, and many dying,
when it entered my house, and my wife was taken ill of it,
I was persuaded to go to a woman who was blind, and pretended she could do great things.
I inquired of her if I should take the distemper,
she being one who undertook to tell what would come to pass: She told me, no,
and I believed her, but when the Lord visited me with sickness,
my disobedience on the one hand, and my believing her,
which I looked upon as distrusting God, on the other,
brought such horror and trouble of mind upon inc, that I concluded, if I should then die,
there were no hopes of mercy for me.

My mother being in great trouble for me, would have comforted me with this,
that I exceeded others in my life and conversation,
but I could not believe there was any favor at the Lord`'s hand for me,
except He should restore me to my health, and I become a new man.
I saw I was not to regard soothsayers, or such as pretend to tell things to come,
they themselves being out of the life of righteousness.
Under this great distress and anguish of soul I cried mightily unto the Lord,
that he would spare me yet a while; and that saying came into my mind,
the prayer of the righteous availeth much;
and knowing not but the priest might be one of them whom the Lord would hear,
I had a mind he should come.
When he came, he wanted his book, and could not pray, so that I was disappointed,
but may say though all other helps failed, yet the Lord never failed,
for be was pleased to restore me, and when restored, inclined my heart to seek after him.
I thought it my duty often to pray to the Lord, in secret places,
to show me his way wherein I should walk, for I was satisfied I was out of the way;
because of the trouble of mind I was under.
As prayer seemed to me to be a duty, I thought it my place to wait upon the Lord,
to feel what would open upon my mind to supplicate the Lord for, and not to pray in form;
but having little answer of well-done from the Lord, I grew weary,
and became more and more formal in my prayers, and my distress increased.
Then I began to doubt that I had not been so diligent as
I should have been in my devotion in the time of our worship,
though I frequently went; so I resolved for the time to come,
I would go to church with the first, and hear and observe every word the priest said;
but I saw all that I could do, signified little: and I was not to sing,
neither durst I open my mouth as others did, but sat solitarily.
Then the Lord showed me the effects of the priests`'
ministry.
They could tell what sin was, and what would be the reward of the righteous;
and what would be the reward of the wicked; but how to come out of sin,
which was the thing I wanted to know, they left me at a loss,
and this lessened their esteem in my view.
I read much of the Scriptures and could talk of them.

In this time of distress, the Lord sent his servants amongst us;
and at a place called Langtown, there was a meeting appointed,
which being about three miles from the place of my abode,
I never heard of it till I was come to the church,
(so called) it being the first day of the week.
When I heard of this meeting, there was such an inclination in me to go to it,
though it was a little past time, that I went in great haste.
When I came, the Friend, whose name was John Wilkinson, was preaching.
He had formerly been an Independent preacher; but I, being so much hurried,
and having an eye out to the exercise some were under,
was but a little reached yet had a great desire to speak with the Friend;
and went into the inn among Friends, hoping to get some discourse,
but not being in the same room with him, was frustrated.
Though I was but a little reached,
yet what he said was afterwards brought to my remembrance, and it wrought like leaven,
and I searched the Scriptures, and thought to have rest there.

Another meeting being appointed about a mile off, there was full notice of it,
to which many went; and Robert Barclay going northward, hearing of the meeting,
came and spoke the word of truth excellently to the people,
so that I could have said amen to several things; and amongst the rest, he said,
"`If a man could begin at Genesis,
and repeat all the Scriptures to the end of Revelations,
and was not led and guided by a measure of that spirit
by which the Scriptures were given forth,
it would avail him nothing.`"
Then I saw, all that I had, availed nothing.
After the meeting was over, and Friends and people were about to part,
there came a young priest and offered some discourse.
I being forward, having read much of the Scriptures,
was willing to join with the priest against Friends;
but Robert Barclay perceiving there was little good to be done,
for there was like to be an uproar among the people, some shouting and making a noise,
there being many sorts of people, took his horse and went away.
But some Friends perceiving I was forward in discourse, cast themselves in my way;
and another young priest that had been at the meeting, took part with me;
and in the hearing of many, we discoursed about many things.
I saw clearly that Friends were too hard for us, though I would not acknowledge it,
and I put on a resolution that I would never more dispute publicly with Friends.

Being come home, and under great exercise what to do,
I searched the Scriptures--read much,
and wanted to be informed concerning many things that Friends held.
In this time Friends appointed another meeting about a quarter of a mile from my abode,
and I had many serious thoughts what to do.
At last I resolved I would go to the meeting, and get near the public Friends,
and hear every word they said; and if I liked them well, I would invite them to my house,
on purpose to discourse with them privately about several things.

While I was under this resolution, one who had professed truth but had proved unfaithful,
coming to work at my house, we presently began to discourse about religion,
though I took little notice of him, because of his miscarriages;
but when he perceived I was dissatisfied with the priests and their doctrine,
he went away home, and brought me a little book written by Francis Howgill,
the title of which was "`Mystery, Babylon, the Mother of Harlots.`"
The reading of this, satisfied me much, and drew me nearer in my mind to Friends;
and I began to say to him
"`Dost thou think if I should invite your friends to my house, they would come with me?`"
He answered, "`If I did so, I would do well; and further added,
that they who gave but a cup of cold water in the name of a disciple,
should not lose their reward.`"
The meeting day came, and many people flocked to the meeting;
and I was diligent to hear the testimony of truth.

Thomas Carleton,
a man of a sweet countenance (as I remember) spake concerning the
spirit of truth being come that convinceth the world of sin,
and that this if taken heed unto, would lead out of all sin;
of which words I was heartily glad, for I said in myself,
"`I have felt that from a child which condemned me for sin;
and if this be sufficient to lead out of sin, it is what I have long wanted.`"
The meeting parted, and people going homeward, I went away serious;
and when gone about two hundred yards from the place where the meeting was held,
it suddenly came into my mind what I had been thinking of the week before.
I stood still to consider what to do; and began to reason that they were strangers to me,
and it was not safe to meddle with them.
I began to go homeward, and had gone but a little way, when I met a Friend whom I knew;
and he asked me about the meeting; and speaking of my satisfaction, I asked him,
if he thought the Friends,
(who were Thomas Carleton and Thomas Langhorn) would go home with me,
for the thing was pressing upon my mind.
Said he, "`Shall I tell them?`"
I said he might.
After he was gone, I began to reason, and was much afraid I had missed my way,
but thought I would stand still to see what they would do.

When they came near, a mighty dread seized upon me,
and I had much ado to abstain from shaking and trembling, that I abhorred myself.
But when the Friends came and took me by the hand,
and asked me if I was willing they should go with me, and I replied, I was,
my strength came to me again; and going home to my house,
the report spread abroad I was turned Quaker, and the Quakers gone to my house.
In a few hours, it being in the winter, and the nights about the longest,
many neighbors came to hear and see; and the house being pretty well filled,
Thomas Carleton and Thomas Langhorn advised me to speak to the people to sit down,
and we would have a meeting.
I did so, and we had a meeting; and afterward several of us, Christopher Taylor,
William Graham of Sikeside, and Francis Story, who was clerk and schoolmaster,
with some others, went to an upper room, and having written some queries, came down.
When the Friends perceived what we aimed at, Thomas Carleton,
being pretty quick and expert in answering questions, called for a Bible,
and did not so much argue with us, as endeavour to let us see what the Scripture said,
putting us gently by, for we were much for arguing: we parted pretty well satisfied.

Next morning the Friends going to Carlisle, Christopher Taylor and I went with them;
and we asked many things, which they answered to our satisfaction.
In our going along, a heavenly melodious song sounded through Thomas Langhorn,
and we were affected with it.
After we had parted, in our return home we said one to another,
"`If there be saints upon earth, those men are two of them.`"

Friends hearing of these things,
J+++.+++ Wilkinson appointed another meeting in two or three weeks after;
and coming to the place, it being a wet season,
Christopher Taylor was desired that it might be on his ground,
on a little hill called Meggs Hill,
(now Friends`' burying ground,) which he readily granted.
There was a very glorious meeting, and many were convinced.

That night Christopher Taylor invited John Wilkinson to his house; and he, his wife,
and his brother Andrew, all received the truth in the love of it, became worthy Friends,
and died in the faith.

After several meetings amongst us, and divers convinced,
we were advised to keep a meeting to wait upon the Lord,
though there were none to speak words;
so we agreed to have a meeting at my house in the year 1672.
Being but a few, we concluded to have it in an upper room of mine;
and when we sat down together,
I may say I was hard beset to keep my mind from running
hither and thither after the transitory things of this world;
and a great warfare I had for the greatest part of the meeting.
Yet near the conclusion, those vain thoughts vanished,
and the Lord was pleased to bring to my remembrance,
how that men who had great possessions in this world, had their day, and were gone;
and I saw clearly, in a little time that my day would soon pass over.
I was comforted in my spirit,
and my inward man renewed in a sense of the Lord`'s nearness; and being thus encouraged,
we kept to our silent meetings, and report went abroad that we had settled a meeting;
and several came and sat down among us.

When there was a public Friend, we mostly had the meeting without doors;
but when only ourselves, we still met in that upper room.
In about a quarter of a year, there was as many as thirty or upwards,
most of them of good repute and conversation:
then we agreed to settle the meeting at four Friends`' houses, and go by turns;
and abundance were convinced, that stood at a distance to see what would become of us.
For the enemy began to rage and persecution to arise;
and because we could not pay tithes, or put into the priests`' mouths,
there was war prepared against us; and a hot time of persecution there was.
Gilbert Atkinson, who had been of repute formerly,
but giving way to temptation and immorality, afterwards became an informer,
made spoil of Friends`' goods, especially Christopher Taylor`'s; and not only so,
but was instrumental to cast Friends into prison.
At this time he was much exalted, and many were ready to think we should be ruined.
Many eyes were over us, some for evil, and some for good.

This informer was so hot,
that nothing would serve him but for Friends to be wholly ruined.
And though he was one that had been afraid to go to Carlisle,
lest his body should be arrested for debt;
yet now he looked upon himself to be so much the king`'s servant,
that he might go any where; and boastingly appearing at the sessions at Carlisle,
lest Friends should get their liberty,
said to the neighbors who were come upon Friends`' account,
that it should be either his day, or the Quakers`', forever.
And when he had thus spoken, the sheriff called for him;
he supposed it had been to prosecute Friends,
but it proved that himself was arrested on a judgment for debt, and was sent to prison.
After awhile Friends were released; but he remained for many years,
and was much afflicted other ways, as well as with poverty and want;
because of which Friends often relieved him, till he died in prison at last.

Here the church was at rest for a time,
and they that had stood at a distance for seven or eight years, came and joined with us.
There were some who thought they might live so as to find acceptance with the Lord,
and not come under the scornful name of Quaker but many came to see at last,
that nothing would do short of confessing Christ Jesus before men;
and all things wrought together for good to them that loved God.
When they that had stood at a distance for years,
thinking to have lived such a life that they might have been equal with us,
saw our innocency and how the Lord had preserved us,
many of them came and joined with us; and among the rest, John Scott of Highberries,
who had been convinced for seven or eight years,
and his life and conversation had so preached among his neighbors,
that many were ready to say "`If John Scott cannot be saved unless he become a Quaker,
what must become of us?`"
Many relations and neighbors followed him, and became honest Friends,
and he himself a pillar in the church.
The Lord`'s lovingkindness continued in sending his servants and handmaids amongst us,
building us up in the most holy faith, and to the convincing of others.
As our love to the Lord increased,
so our care increased in keeping to our silent meetings.
Glorious and heavenly times we had, when no words were expressed.

Some years after our convincement,
being met in the house of Christopher Taylor to wait upon the Lord,
his power and presence in a wonderful manner overshadowed us in our sitting together;
and there was much brokenness and tenderness on the spirits of Friends,
which spread over the whole meeting, except three or four persons who sat dry,
and they proved not well.
I being near the door, saw many in the room filled,
before the power of the Lord reached me: yet the Lord, in his free love and mercy,
was pleased to give me such a share among my brethren,
that my heart is always glad when I remember that season of God`'s love,
though now upwards of twenty years ago.
And though we were at times plentifully fed with that bread which came down from heaven,
and sat together at the Lord`'s table,
where the wing of his power was known to overshadow us;
yet at other times the Lord tried us with want;
and at a certain time it entered my mind as a weighty
consideration why it should be thus,
we being the same people, and sometimes had very good and comfortable meetings,
and were sometimes very dry and barren in our meeting together.
As I was thus concerned in my mind, it opened to me,
that there should be seed-time and harvest, summer and winter, unto the end of the world.
So I saw clearly there were times to abound, and times to suffer want;
and I desired to rest satisfied in the will of God.
As we sojourned here, desiring nothing more than to follow the Lord fully,
he not only led us out of the gross evils which are in the world,
but out of the customs and fashions that are evil.
So that we were singled out from the world in everything we saw to be needless and superfluous:
and the fame of truth spread, and our meetings were large,
and the exercise of the faithful was to draw nearer and nearer to the Lord.
And when a little child`'s state was witnessed in
our meeting together to wait upon the Lord,
having the mind retired for a considerable time until the Lord
was pleased to appear and fill our hearts with life and power,
it made some of us to say, a little child`'s state is a good state,
and we greatly desired to remain here, where the glory of the Lord filled the temple.
This made us beautiful,
though we were not come so far as to have a word given us
to speak unto others by way of testimony publicly;
and though it was the desire of some to have remained here, yet the Lord,
in his own time, gave them to experience, that the Gospel, which is the power of God,
is not received but by the revelation of Jesus Christ:
neither is this Gospel to be preached in the will of man, or in man`'s time,
but in the Lord`'s time.
And though it is written, "`Quench not the Spirit,
despise not prophesyings;`" yet many have been unwilling to speak the word of the Lord,
though it hath burned as a fire in their bones,
and they have been filled with it as a bottle with new wine,
lest they should offend the Lord, or burden his seed in the hearts of his people.
This hath made some say, "`Lord,
let me never speak a word in a meeting while I live in this world,
rather than I should speak that which might offend.`"
And though some may have been too backward for a time,
and there may have been a sense of trouble for it, and judgment from the Lord,
yet it being in a godly fear and awe, lest it might prove an untimely birth,
the Lord hath been merciful unto such,
and hath again and again appeared and not only brought
to the birth but enabled to bring forth:
and as the work is his, the praise and glory belong to his great name.
In the Lord`'s time, to us that had been under the region and shadow of death,
light sprang up; and our mouths were opened, and tongues loosed,
to speak well of the Lord.
The Lord raised up planters and waterers,
and made several as useful instruments for carrying on his great work in the earth.

After I was convinced, and had joined myself to Friends,
as I received the truth in the love of it, my love greatly increased to the Lord,
and to his people: I was diligent in going to meeting at home,
and often had a desire in my mind to no to other meetings and sit among Friends in silence;
and many times was sweetly refreshed, and returned in peace.

About four or five years after my convincement,
I had it in my mind to go to several meetings in our county;
and the first I went to was Wigton, their week-day meeting being on the fourth-day;
and sitting down in true silence with my mind stayed upon the Lord,
those words sprang livingly in me,
"`The year of the jubilee is now come;`" and they operated in me to that degree,
that I had much ado to contain;
but being fearful to open my mouth in the assemblies of the Lord`'s people,
I reasoned till the life and power withdrew; and though the words remained,
I saw I could do nothing, having quenched the spirit: judgment seized upon me,
and I was under trouble and exercise for my disobedience.
Being inclinable in my mind to go to the other meetings,
I greatly feared what I should do if the Lord appeared again as he had done,
for to give up to speak a word in the meetings of
the Lord`'s people was a thing very weighty to me;
and to undergo his judgments as I had done, was very heavy;
and therefore I desired in my mind, the Lord might not appear to me in that manner.
To the next meeting I went, and was still and quiet, and pretty easy in my mind;
and on the sixth-day we had a meeting for business for our county,
and I was glad to see Friends.

On seventh-day I went to the Holm, to be at their meeting on the first-day;
and as I went, I desired the Lord might not appear as he had done,
for I much dreaded the Lord`'s appearance.
When I came, the Lord withdrew, and left me to myself; and I was so poor and weak,
I could scarce forbear falling asleep,
though I had known so much of the Lord`'s goodness to my soul for many weeks,
and some years, that if I had been sleepy when I came into a meeting,
through the Lord`'s help, sleep would have vanished.
This proved such a surprise to me, that I said within myself, I will go home,
and mourn out my day.
The Lord, who knew the intent of the heart, saw what was the cause of my backwardness,
which was lest my ministry should not be as ripe fruit; and I often desired of the Lord,
that I might never speak a word in that way while I lived,
rather than I should speak that which might burden his seed in the hearts of his people.
I remained for several weeks under great exercise of mind,
lest I should be forward and miss my way,
and bring trouble upon myself In this time the Lord
often filled my soul with life and power,
and gave me his word; but through fear, I fell short in publishing it, because of which,
I was often under judgment; and then thought, if the Lord would but appear again,
I would give up.
But time after time, though the Lord did appear, I fell short and quenched the spirit.
An ancient solid Friend perceived it, and spoke to me to give up.
And at last, being in a week-day meeting at John Ivison`'s in Jerrish town,
I was filled to that degree with life and power, that I could not contain,
but spake forth these words as they sprang in me, "`that they that sat in darkness,
had seen a great light; and they that were under the region and shadow of death,
to them light is sprung up: glory to God forever.`"
And as I thus gave up to answer what the Lord required of me,
I had abundance of peace in my own mind, and cause of rejoicing.
This was in the beginning of the winter, in the year 1677.

I remained at home until the spring;
having had something in my mind for some time to visit Friends in Scotland,
if any Friend was going who wanted a companion.
In the second month following, a Friend from Yorkshire, whose name was Edmund Winn,
going for Scotland, wanted a companion.
I made ready, and went along with him.
The first meeting we had in that nation was at Allassudin, where Walter Scott lived,
who had been early convinced, and suffered for truth: and being a man of an estate,
the meeting was kept in his house.
But when we came,
he refused to have the meeting in his own house or to go to it
when it was held in another Friend`'s house in the town,
alleging that meetings were but a form and every man might
worship God as well in his own house as in a meeting;
and so withdrew himself.
Both he, and several of his children that were once hopeful, forsook truth and Friends,
and the meeting was lost afterwards.

We visited Friends till we came to Aberdeen,
where we found the greatest part of men Friends in prison,
and had been for near two years; amongst the rest our friend Patrick Livingstone,
whose habitation at that time was in England.
Being come there to visit Friends, the magistrates of that town were so severe,
that what men Friends they found at the meeting they put in prison:
and though they had set them at liberty several times,
yet finding them in the meeting again, they committed them to prison,
where Patrick Livingstone continued, with several others,
until their persecutors were wearied, and let them have their liberty.
We being there about that time, and having grown weary, they took no notice of us.
And though by this time I had received some little strength,
that I could (but not without fear) speak a few words in a meeting,
when I believed I had them rightly given me in the life and power of Truth;
yet it had never been required of me to supplicate the Lord in public;
and this looked to me a more weighty matter to do,
than to speak a few words in a meeting.
Being in a meeting at Aberdeen, it was upon me to pray unto the Lord,
and I was hardly beset in my mind how to give up;
and another Friend kneeling down to pray, made way for me to follow, and I was easy.
