== Chapter II.

[.chapter-subtitle--blurb]
1678--1687.

[.chapter-synopsis]
* Return from Scotland
* Religious Service in part of Yorkshire, etc.
* Visit to George Fox
* Attends the Yearly Meeting in London
* A time of Persecution
* Much Convincement

Having visited Friends in the north, where there was great openness,
several were convinced,
and divers amongst themselves livingly opened by way of testimony,
we returned for England again, and staying at home that summer,
I bad it in my mind to go and see George Fox, whom I had never seen,
and who was then at Swarthmore; and the time that was in my mind to go,
was after the harvest was over.
But when the time drew near that I intended to set forward,
it was before me to visit divers meetings in Westmoreland, and in the dales of Yorkshire,
in my way: and a Friend going along with me, we went forward,
and visited meetings all along until we came to Wensleydale in Yorkshire,
where we found great openness amongst Friends in their meetings.

In Wensleydale meeting, there was so much brokenness and tenderness among Friends,
that after I had said a little, I sat down in silence;
and it opened in my mind to speak of the Lord`'s appearance unto the prophet,
not in the earthquake, nor in the rushing wind, but in the still small voice.
From thence we went to Swaledale; and though the Lord was near in meetings,
and his comfortable presence and opening life I was a witness of, yet many times,
when out of meetings, I was loaded and much under exercise of mind,
and did not know what was the cause.
At last I began to think I had missed my way in coming into those parts;
and if I did not grow more easy, I would return home: and being at the widow Cherrie`'s,
I was in the fields a little before the meeting;
and not being much acquainted with the weight of a testimony,
was much cast down in my mind.
Being come into the house, after a little time came in Richard Robinson of Wensleydale,
whom I know to ha a weighty ancient Friend;
and having been at their meeting the day before,
began to fear he had something against me,
for I perceived by his own words he was come on foot six miles;
and he said he had not done the like for several years.
Concluding in my mind he was not come for nothing, I resolved,
whatever he had to say to me, I would take it well,
and withal I thought I would say but little if I could help it.
The meeting being gathered, after some time I could not easily forbear,
but I must say what opened upon my mind, in the spring of love, and after I had done,
Richard Robinson appeared, and confirmed what I had said, and was, with other Friends,
loving and kind.
But after all this, when we were parted, I was under exercise again, as much as before,
and this being on the sixth-day, we intended for Masham meeting on the first-day,
and in our going, I concluded if I was not more easy, I would appoint no more meetings,
but would go home.

After I sat down in the meeting,
I found the Lord was near to supply those that had their dependence upon him;
and after I had spoken what was upon my mind to the meeting,
Robert Lodge said on this wise: "`It is now, as it was in the days of old,
when the priests of God went mourning, between the porch and the altar,
not because of their own sins, but because of the sins of the people;
and now many are made to go mourning between meeting and meeting,
not for anything they have done, but for the sake of others.`"
This eased me greatly of my burden, and I was helped on my way,
for which the Lord shall have the praise.
Taking meetings in the way, I came to Swarthmore on the seventh-day,
and was at their meeting on the first-day, where was George Fox, Margaret his wife,
and four of her daughters, and all very loving and kind; when we parted,
George exhorted me to keep to the grace, and I should grow.
After this I came homeward, had some meetings by the way,
and remaining at home in the winter, had a desire to go to the Yearly Meeting at London,
but supposing there were many weighty ancient Friends, in the county,
who were much more qualified, I was unwilling to speak of it.
Being at our county meeting, which was of the nature of a Quarterly Meeting,
but kept oftener, at that time inquiry was made of all the particular meetings,
who intended for the Yearly Meeting at London, and none appeared to go in all the county,
but John Banks; and when the meeting w-as far over,
and I perceived Friends were desirous there should be another Friend at least, to go,
I desired a Friend to tell John Banks if he would accept me for a companion,
I would offer my service to the meeting: he told me, if I had a desire in my mind to go,
he was satisfied I should go with him, but he would not draw me.

The time being short, I had to make ready; he appointed to meet me at Great Strickland,
and wished to have a meeting.
Accordingly I went, and we had divers meetings by the way,
in which John Banks had good service, and I was well satisfied with his company.
This Yearly Meeting was in the year 1679, and the first Yearly Meeting I was at,
and a good and glorious meeting it was to me, and many more;
who were wet plentifully with the dew from heaven:
and that which confirmed us the more was to see the
aged and the young keep their places in humility,
endued with heavenly wisdom,
that nothing which tended to strife and contention could appear without rebuke,
in order that love, unity and concord, might be maintained in the churches of Christ.

After the meeting was over.
Friends parted in great love and unity: we went towards Bristol,
and had many good meetings in divers places in the way,
and also in our return to Cumberland.

Calling at Swarthmore, we stayed their firstday meeting,
where we had George Fox`'s company, who inquired of the affairs amongst Friends,
and of our travelling from place to place, where the Separatists^
footnote:[These Separatists were the party who left the Society with Wilkinson and Story,
in consequence of their dissatisfaction with the Discipline.]
dwelt; and what openness there was in places where we came,
to hear truth`'s testimony declared; to all these John Banks gave him a full account.
After this we journeyed home, and I found several Friends in prison,
and the informer in prison with them, as I have related before.
This was a time of hot persecution, in the reign of King Charles II.;
except between the time of the first informer`'s being put into prison,
and the other taking his place; in which time I visited Friends in Scotland,
and afterwards Andrew Taylor and I visited Friends in Lancashire, Cheshire,
and some places in the west of Yorkshire, in the year 1682.
There was fining Friends, and putting them in prison in most places where we came;
and in our return homeward, we came to Sedbergh in Yorkshire,
and having heard that Friends had suffered a great deal in Dent,
and were still under suffering, we concluded rather to go by than to add to their bonds;^
footnote:[This expression will be better understood when it is stated,
that the law under which Friends were persecuted imposed a penalty of
twenty pounds for suffering a meeting to be held in a house or barn,
and twenty pounds for each preacher who spoke in the meeting--both to be levied
on the goods of such Friends in the neighborhood as were able to pay.
The apprehension that their appointing a meeting at Dent
might thus bring increased suffering on their brethren there,
and expose them to be afresh plundered by the informers, operated as a discouragement,
and induced them to "`conclude to go by rather than add to their bonds.`"]
and being at Sedbergh the night before, we were intending to come home,
but an exercise came upon me in the night, my sleep went from me,
and I could see no way to have peace, but to go to Dent.
At last I gave up, and when the morning came, told my companion I must go to Dent,
and we acquainted some Friends with it.
They told us we might expect a prison,
for there was a warrant signed by several justices to apprehend
any strangers they found preaching in Friends`' meetings,
upon suspicion of being Jesuits; but having concluded in my mind, I was resolved to go,
and I would have had my companion to tarry, but he had more freedom to go.
So on the first-day morning we went, and Edward Atkinson, of Syde, with us.

When we came into the Dale, Friends were going to the meeting, and other people also,
and we told them we were come in love to visit them,
but it was with some concern of mind, lest they should be fined on our account;
but they answered, there was nothing in that,
for they were fined already more than they had goods to pay with.
We came to the meeting, and divers, both Friends and others, being there,
after some time Andrew Taylor stood up, and had good service, but before he had done,
several constables came in, and required him to go along with them,
but he taking little notice, some Friend that was near,
prevailed with the constables to forbear a little, till he had done,
and they went out awhile, but thought he continued long, so they came in again,
and commanded him to go along with them, by virtue of the warrant,
which was signed by several justices.
Being present, among many others, I desired to see the warrant,
yet they took no notice of me: and after some discourse,
the constables were willing to dismiss him,
upon promise of two Friends that he would meet them at Dent town the next morning.
This being done, we continued our meeting until Friends were free to part,
having had a good opportunity, to the satisfaction of most that were there.
Several were reached and tendered,
and Ann Knowles was convinced and continued an honest Friend.

The next morning we went to Dent town the constables thought it
needless for them all to go with Andrew Taylor to justice Otway,
and therefore agreed that only one should go.
As we went, I was much concerned about my companion`'s going to prison,
and my going home without him; for his mother not being of our persuasion,
and this one of the first journeys he took to visit Friends,
I expected she would blame me, for she loved him well.
Having an opportunity, I informed the constable, that if he did not take an oath,
but only brought him before the justice, it might be he would not send him to prison:
and that if he took an oath, he would be the informer,
and would have the trouble of conducting the Friend to York, which was sixty miles,
or otherwise cause Friends to be fined.
To be an informer the constable much despised, and therefore resolved to be favorable,
and coming near the place, being many in company,
we agreed that Andrew and Richard Harrison of Dent, should go with the constable,
to the justice`'s house, and we would go to an inn in Sedbergh, until we heard from them;
and parting, they came to the house.

It being a wet day, the Friends stayed under a shade,
and the constable went in to acquaint the justice, and meeting with him, told him,
he had found a stranger in the Quakers`' meeting, and had brought him thither; he asked,
if he preached: he answered "`Yes.`"
"`What said he?`"
said the justice.
"`Nothing but well,`" said the constable.
"`However,`" said the justice, "`you must take the oath.`"
"`For the Lord`'s sake,`" said the constable, "`excuse me, for I will not swear.`"
The justice being a lawyer, and perceiving the man in good earnest,
after he had considered a little bid him go his way; and coming to us at Sedbergh,
we entertained him civilly, and he rejoiced greatly in what he had done.
Parting with Friends in great love, we came home,
and a new informer having made information against me, with several others,
for having a meeting in my house, I was fined twenty pounds, when I was in Lancashire,
forty miles off.

Notwithstanding the endeavours of our persecutors, truth prospered,
and there were many added to the church,
insomuch that our dwelling- houses were too small to keep our meetings in;
so we saw it needful to build a meeting- house, and purchased wood of Henry Dacres,
for that purpose.
But the priest with some others, petitioned the bench of justices,
in the time of sessions, not to permit us to build a meetinghouse,
for they alleged if we built a new chapel, they might pull down the old church;
for by this time, people`'s eyes were so much opened,
that though the parish was five miles in length,
yet sometimes not above five besides the priest and clerk, were there.
Three clerks were convinced, one after another, and came among Friends,
though one of them fell away, yet he never would be clerk again.
One of them being a conscientious man, told the priest, whose name was Robert Priestman,
he could not say Amen to him, for he saw the priest himself was short.
The priest replied, he might say Amend, but all would not do, so he left him.

The sessions, considering the premises, wrote to Dacres, who was a justice of peace,
to let us have no wood, neither would he give us our money again;
and wood being in great men`'s hands, they hearing this would sell us none for money,
in this part of England.
Toward the end of the reign of King Charles II.,
when great severities were practised against the dissenters, the old priest died,
and one George Story, a young man, getting the place,
and being not much acquainted with Friends`' integrity to the Lord,
in suffering for his name`'s sake, at a certain time he spoke to me,
that if we would not suffer Friends who lived in other parishes to come and meet with us,
he would not molest us; but if we would meet constantly in our parish,
and allow Friends of other parishes to come and meet with us, he would not suffer it.
We not complying with his proposal, he was hot in his mind for persecution,
and they began with Sunday shillings, as they called them,
for not going to the public worship, and made distress of Friends`' goods.
But this they thought did but little,
and afterwards the said priest caused the wardens of the parish of Kirklinton
to frame a bill at the assizes against several of us,
and indicted us as popish recusants, for not coming to their worship.^
footnote:[This was by virtue of a law made in the reign
of Queen Elizabeth for the suppression of popery,
authorizing the levy of a fine of twenty pounds sterling per month,
on the goods and chattels of all such as absented themselves from the established worship,
and acknowledged the supremacy of the pope in matters of religion.]
Processes were issued out against us for twenty pounds a month;
and our meetings continuing large, the priest greatly wanted an informer;
but because of the ill success they that were engaged in it before met with,
sober neighbors would not meddle.

At last one James Appleby, a Yorkshire man, brought up at school,
and having some knowledge of the law, undertook the office of an informer.
He persuaded one Christopher Story, that lived at Allergarth, to join with him,
and in the tenth month, 1682, they came to my house, the meeting being there,
and made information to Henry Forster of Stonegarthside, a justice of peace,
of several being met together.
Ho asked him if I was at home: my name being amongst the rest, he said I was,
as the justice reported, although I was in Lancashire,
above forty miles from my own house that day.
A warrant for distress came out, but I being gone from home above two weeks before,
and not returning till six weeks after, the officers forbore to make distress,
and the informer was at that time disappointed, perceiving his mistake.
Though the informer had sworn falsely,
yet they were so much encouraged by the government,
that little could be done against them.
Towards the latter end of summer, seeing himself likely to escape the danger,
they came again to my house and took an information,
and went to John Aglionby of Drawdykes, a justice,
and a warrant was put into the officers`' hands,
who were so sparing in making distress that Richard Scott of Newbiggin,
was bound to good behavior for neglect of his office.
Most of what was about my house being seized on,
they proclaimed a sale-day at public markets and other places; but as none came to buy,
except James Appleby, the informer, and one man that he brought with him,
they had things at their own rate.
Two horses he took to a fair in Northumberland, and sold them under half price,
for neighbors would not buy them.

Driving the sheep away, young people that were not Friends being grieved to see it,
set dogs upon them; and the noise being heard, other people,
almost in every place where they came, ran out with their dogs, and scattered the sheep;
so that when the informer and others had followed full two miles,
they had but seven left, and were greatly vexed thereat.
When he sold them, and had made fast the barn doors +++[+++where my grain was]
with locks and chains, he used endeavours to hire threshers,
but could not get any for money in the country; so hired a man at Newcastle,
forty miles distant, and was to give him twelve pence a day, meat and drink,
whereas the usual price is but four pence.
The man coming into the country, and people understanding his business,
before he came to the informer`'s house, or scarce within five miles of mine,
they persuaded him to turn again,
telling him some dangerous thing would befall him if he meddled.
So he returned again, and would not thresh for money.
The informer being then persuaded he could not get it threshed,
unless he had it carried away from the place;
and his daughter being married to a near neighbor of mine,
he thought to have removed the corn thither; but her father-in-law, being an old man,
would not consent for fear of danger, saying, "`Some will burn it,
and my houses also;`" so that though there was a great deal of corn,
he had no power to get it: but selling other corn and things taken from some Friends,
he made a purse, went to London, and made complaint against us to Jefferies,
then lord chief justice, and brought subpoenas against sixteen of us,
to appear at London; but we understanding a prison would do, whether we went or not,
resolved to abide at home.
Upon our not appearing,
he went to London again and made complaint against justice Forster.
Judge Jefferies coming the northern circuit,
the informer indicted us several times for meeting together,
and called our meetings riots, routs, and unlawful assemblies;
endeavouring by a warrant to make us appear before Jefferies.
But the constables hearing, and partly believing, that we should then be ruined,
(for he had indicted about twenty of the most substantial amongst us,
as he supposed,) would not be seen by the informer,
till it was too late to bring us before Jefferies.

At this assizes, justice Forster was fined one hundred pounds,
and imprisonment till paid, and put out of his place,
which caused some of the justices to be afraid.
The informer being high in his mind, and his money almost spent,
came to our meeting again, and brought with him his son-in-law, George Waugh,
and carried his information to Henry Dacres, a justice,
(so called) and obtained a warrant.
I, being fined twenty pounds for preaching,
the officers took several cows and young beasts, and drove them to the market;
but not being willing to sell them,
set men at a little distance to tell buyers what sort of goods they were;
and also asked above the market price for them.
The informer perceiving it, made information to the said Dacres of their neglect,
and one of them, George Irwin, was bound to good behavior.
But some responsible men, particularly Edward Atkinson of Clift,
went and prevailed with Dacres to forbear a while, it being the beginning of winter;
and with some distress of Friends for small fines
to quiet the informer a little till the spring.
In that time King Charles died, and the informer`'s strength decayed,
and none of the justices would hear him; so they never sold the goods formerly seized.
We, being bound over to the assizes, appeared; our indictments were read,
and we required to answer Guilty, or Not Guilty.
We confessed we met together to wait upon God,
but not in that manner they represented us which they took for a traverse,
and demanded fees and bond to prosecute,
which we denying were sent to prison and there remained until King James,
by his proclamation, set us at liberty.

Though much time was spent by the said James Appleby and others,
who used all their endeavours for about three years to break our meetings,
impoverish our families, and imprison our bodies;
yet I can say all things wrought together for good to them that loved God.
For in this time of persecution, which continued near three years, we lost but one man,
and several were added, and many gathered near to the Lord; and we had glorious meetings.
I may say it was a time of love.
Whereas the officers usually came to disturb us in our meetings,
they were now commanded to see that none molested us there;
and at once we were freed from the heavy burdens our adversaries had cast upon us,
and our meetings grew large, and many flocked to hear.

Now our necessity increasing for building a meetinghouse, and seeing no better way,
we went to Scotland and bought wood,
and built an house that would hold one-third more than we then were,
but in a few years it came to be filled.
The Presbyterians, who had hid their heads for years, began to come forth again,
and built a meetinghouse in the border, about four miles north of us,
where they met for a time; but after a while dropped their meeting,
and the house went down, and truth prospered.
We saw that many wanted to be informed of the right way of the Lord;
and a meeting was appointed near the place where the Presbyterians had built their meetinghouse;
and glorious meetings we had: many were much reached and convinced.

Amongst the rest that came and joined with us after the persecution was over,
Aaron Atkinson was one, who was of believing parents convinced almost with the first,
and of good repute in the country:
his father lived but a few years after his convincement;
yet bore a good testimony for the time.
After his decease, his wife, whose name was Ann, dwelt near the Lord;
and her heart was filled with love to God and his people;
and though she was left with six small children, and not much outward substance,
yet she was not at all cast down under her exercise: for the Lord sweetened her passage,
and made hard things easy, that she remained bright and cheerful in her countenance.
After some time she sickened, and I went to see her, being four or five miles off;
when I came, I found her in a heavenly frame of spirit, and resigned to die:
and she was not anxious for her children,
but fully believed the Lord would take care for them:
thus in a few days she sweetly finished her course.
Her children were mostly provided for by Friends and relations.
In their young days they proved generally vain and wanton for a time;
yet remembering the faith which was in their mother, I expected to see their restoration;
which in due time came to pass.
For Aaron, when he was but young, and carried a linen pack on his back,
being at William Graham`'s of Sikeside, his near kinsman,
went to an evening meeting at Christopher Taylor`'s; and in the time of prayer, the Lord,
being supplicated that as he had been pleased to
visit the fathers he would visit the children,
graciously answered that supplication; and reached Aaron by his power,
that he was as one slain at once, and freely giving up,
went out in the faith and greatly prevailed.
His master, William Armstrong, who was a Presbyterian, hearing of it,
was at a stand what to do with him; yet concluding we were an honest people,
he would try him further; and after some time, his master was convinced also;
and they lived together in much love, and honored truth in their trading,
being at a word with people.
Though they lived near Scotland,
they saw they were not to trade in goods which were prohibited, as many did;
neither were they free to sell such striped or gaudy
cloth as was not seemly for Friends to wear.
And as their acquaintance was great, and their integrity well known in the country,
by being preachers of righteousness where they were concerned among men;
so the Lord raised them up,
and gave them living testimonies publicly to bear
in the power and demonstration of the Spirit.
Aaron was first concerned in a very powerful manner,
to the reaching of the hearts and consciences of many.
And then William came forth, and many people who knew them had a desire to hear them,
and many meetings were kept at fresh places up and down the country,
and people that were not Friends would come three or four miles to our meetings frequently;
so that in time our meetinghouse became too little,
and people that were not Friends would send to us to have meetings on their ground.

A great openness there was in the country, and amongst others,
all Aaron Atkinson`'s brothers that were living joined with Friends,
and walked circumspectly; his sister also came, but died some time after.
Honest Friends, of what employment soever,
were then concerned to be testimony-bearers in the way of their trade and business;
and though it looked for a time as if it would have hurt their trades,
yet as Friends were faithful, and preserved in a meek and quiet spirit, they prospered;
and though some had but little when they were convinced, their endeavours were blessed:
for being diligent in the management of their trades and affairs,
and carefully keeping their words and promises, they gained credit in the country.
