== Chapter III.

1687--1699.

Visit to Friends in Ireland and in several parts of England--Some occurrences
in his own county (Cumberland)--Journey to Scotland--Ill treatment at Glasgow--Visit
to Friends in the Western and Southern parts of England--Further services;
much of which not particularly noticed--An Epistle to Friends.

In the year 1687, I travelled into Ireland to visit Friends;
it was in the beginning of the troubles that happened in King James`'s reign;
and was a dismal time, few nights passing where I went without houses being broken open,
and English and Scots plundered by the native Irish.
The dark power they were under was a load to my spirit,
and my greatest concern of mind was to bring Friends to the enjoyment
of that which man could not give or take from them;
that though the fruit of the olive should fail, and the earth not yield her increase,
nor any flock be in the fold, yet they might joy in the Lord,
and rejoice in the God of their salvation.
When I was clear, I returned home, and found my family well.

In the year 1689, John Bowsted and I travelled through Lancashire, Cheshire,
Staffordshire and Gloucestershire, to Bristol, having many meetings in divers places,
and found great openness both amongst Friends and other people.

After we were clear of Bristol, and had visited Friends in many places,
we travelled through Wiltshire, and visited most of the meetings in our way,
by Reading and Windsor, to London.
We found great openness in and about that city;
and when we had visited the meetings there and were clear, we took meetings on our way,
toward Banbury,
and a great openness there was amongst people in divers parts in that country,
and coming towards Birmingham and Wolverhampton we parted,
and John Bowsted travelling into Wales to visit Friends, I went home.

About this time, George Story, priest of the parish, whom I mentioned before,
hired a curate, and went away, and was a chaplain in King William`'s army,
when they went for Ireland, and afterwards became dean of Carrickfergus.
He was kind to Friends,
and though he had a demand of tithe on a great many of us for several years,
yet rather than cast us into prison, he went without it to this day.

Truth having appeared,
and the understandings of many being opened by the Divine Light thereof,
we were led out of many customs and practices,
which we saw were attended with bad or disorderly consequences; and amongst the rest,
a custom generally practised by people in our country, namely, making doles at burials.
When we were first convinced, that practice was grown so common,
and to such an extravagancy, that great numbers of people came to burials,
both rich and poor without invitation,
and as people were very extravagant in many things, this became a snare to some,
and an uneasiness to us, and we could see no real service in making such doles,
when people were met together on such a weighty occasion, but on the contrary,
great disorders often happened.
Under a serious consideration we had a stop in our minds,
and could not follow the people of the world in that custom,
therefore we thought fit to break it off at once, which we did,
and gave nothing at that time to poor or rich.
After a little time, the people saw it to be a good way,
and came from doing much to doing but a little; they frequently came to our burials,
and that in a great deal of seriousness; scarce an high word among them.
Then we observed time and room enough to keep a meeting,
and good seasons we had many times, to the satisfaction of Friends and others.
So that I never yet heard of any complaint for want of outward bread,
but many have acknowledged the satisfaction they had,
in partaking of the inward bread that was broken at such times,
and great service there was among the people.
When Christopher Taylor was laid in his grave,
who was a just man and of good fame in the country.
Friends and relations with many others met together
to accompany his body to the burial place,
where the Lord was pleased eminently to appear through his brother, Andrew Taylor,
a worthy instrument to the convincing of many of the right way of the Lord;
and when that saying was spoken of to the people, how the prophet Samuel said,
"`Whose ox, or whose ass have I taken,
or whom have I defrauded,`" the like answer was returned in the hearts of the people,
that the deceased had wronged no man.
And the Lord`'s presence greatly appeared; many were deeply affected,
and several convinced.

As the church increased, a godly concern came upon several,
to promote a strict Discipline therein, that as there had been a coming out of Babylon,
there might be such a separation, that that which was unclean might not be touched,
and this became a hard thing to some, to cast off and forsake all their old lovers:
yet the Lord owned his people, and truth prospered,
and many were willing by the grace of God,
to put their hand to help forward this good work,
and their shoulders to bear a part of the burden, and so the work became more easy,
few appearing to oppose good order in the church;
for which the Lord shall have all the praise.

Our meeting-house being too little,
and a part of our Friends living three or four miles northward, beyond the River Line,
which being difficult to get over, having neither boat nor bridge,
with consent of Friends, they established a meeting among themselves, in the winter,
and after some time built a meetinghouse, except that once every month,
they met with us at Sikeside, and also on the week-days.

In the year 1691 I travelled into Scotland, having Thomas Blair with me.
I had it in my mind to go and see a few Friends at Glasgow,
for at that time there was no settled meeting there.
We travelled to Edinburgh, and so to the north, and back again into the west.
Coming to Gartshore,
after the meeting I acquainted Friends that I had in my
mind to go to Glasgow and visit the few Friends there,
and inquired if any Friend would go along with me, but some excusing themselves,
and I being resolved before hand, said if none of them would go, yet I would,
and coming there I found the people so barbarous,
that I did not think there had been any such in the three nations.
I felt a little of it as I came towards Gartshore, and set my face westward:
I thought I felt a great cloud of darkness,
yet having travelled several times through Scotland, and been in many places,
both in England and Ireland,
I did not think they would have been so cruel as they proved.
James Milner and John Milner went with us to Glasgow,
where putting up our horses at an inn, we sent for our friend John Hewstown,
and told him we were come to see them,
and inquired if we could have a little time with Friends; but his wife being no Friend,
and the people very cruel, she was not willing any meeting should be in their house,
whereupon our friend John Neile, having a child not well, we went thither,
and being retired a little, something opened upon my mind to speak.
After I had said a little,
on a sudden people came rushing into the house in a rude manner,
as the following account will show, and stoned us out of their town with great severity.
We went that night to Hugh Wood`'s of Hamilton with
a great deal of peace and comfort in our own particulars.
There we wrote the following account:

A Looking-Glass for the Inhabitants of the Town of Glasgow.

We Christopher Story and Thomas Blair,
being come from our habitations in the county of Cumberland,
to visit Friends in Scotland, were in the pure love of God drawn to Glasgow.
John Milner, of Gartshore, and James Milner, of Hamilton,
in the same love and in the freedom of their spirits went along with us,
and meeting with our friend John Hewstown,
we went to visit our friend John Neile and his wife,
they having a child not well and after we had waited a little together upon the Lord,
to feel his power and enjoy his presence, we can safely say, the Lord was near us,
so that I was made willing, in obedience to the Lord`'s requirings,
and spoke of the great joy and comfort that was received in the Lord`'s presence,
desiring nothing more than this,
that all people might be sensible of the goodness of God held forth unto mankind,
in and through his Son Christ Jesus; also exhorting the people to turn unto the Lord,
and believe in the light, that manifests sin and evil,
showing unto all according to plain Scripture,
that it was sin in all ages that separated between man and his Maker,
and it was iniquity that withheld good things from him, etc.

For this cause and no other given by us many cried with great bitterness against us,
surrounding the house, knocking at the windows, women as well as men, with great fury,
saying, "`Pull him out, pull him out,`" seeming as if they would have torn us;
but others of them were more moderate and seemed inclinable to hear,
if the rabble would have been quiet.
At last there was an uproar amongst them, and they quarreled one with another,
at which time I became silent, and a young man amongst them more uncivil than the rest,
named James Bear, a Presbyterian, as he said, and no magistrate,
neither had he any warrant, with some others, would hale us out into the streets;
but after some arguing with him and wishing that
this day`'s work might not be laid to his charge,
he was more quiet.
Then John Hewstown seeing their incivility,
exhorted them to moderation with some other Scripture words of brotherly advice,
lest their bonds should be made stronger; at which some scoffed; others said,
"`We could fain hear you preach, for we never heard Quakers preach.`"

A little after, not being clear in the sight of the Lord,
I was concerned to clear my conscience, and spoke to the people according to Scripture,
that except our righteousness exceed the righteousness of the scribes and pharisees,
we could in no wise enter the kingdom of heaven; endeavouring,
by several Scripture passages,
to prove the necessity of first making clean the inside of the cup and platter,
then the outside will be clean also,
that they might not be liable to the woe pronounced against the scribes and pharisees.
Then came in one thronging among the people, whose name was John Sprewell,
tobacco merchant, and pulled me violently out of the house.
When I was out of the doors, the rabble laid hands on us,
as if they would have torn us to pieces;
but the said Sprewell hailed us to the magistrates, and commanded the rabble to be civil,
but they cried and shouted, and threw dirt and stones at us through the streets, saying,
"`He is a Jesuit dog,
he hath spoken blasphemy;`" but none of them offered
to prove anything against any of us.

We were brought before bailiff Brooke, one of the magistrates,
who when he understood the matter, said he had not time then to hear us,
but he would call us at another time.
But the said John Sprewell desired earnestly that he would detain
us till some of their teachers were brought to examine us.
Yet notwithstanding the magistrate dismissed us,
and Christianly desired the said Sprewell to preserve us from the rabble;
Sprewell went away, and left us to the will of the rabble,
who stoned us all along the streets to the house of James Bisben, innkeeper; yea,
hundreds of men, women, boys and girls, followed us, casting stones, coals,
and dirt at us, Sodom-like, notwithstanding all their profession,
when we were come into the aforesaid house to get some refreshment for our money,
the rabble encompassed the house, looking in at the windows where we sat,
abusing us with their tongues and spitting in upon us.
When we took our horses to go away, they abused us in like manner, as aforesaid,
all along the streets to a place called the Draygate.

Now if the tree must be known by its fruits,
let all sober readers judge from what spirit those fruits aforesaid proceed:
and though we have not given so full an account as we would, yet,
we think what is here said will show the evil of such actions to other nations,
and to generations where these shall come, whatever their profession be.
And we heartily desire that the great God of heaven and earth,
who still seeth the afflictions of his people, may forgive our persecutors,
and convince them of the evil of their ways, that they may do so no more,
lest a worse thing befal them.
For a confirmation of this testimony, we subscribe our names,
and appeal to all sober persons that beheld it.

Christopher Story, Thomas Blair.

The 4th day of the 4th month, 1691.

About a week after, Robert Barrow and John Thompson of Westmoreland came there,
and they abused them, and endeavoured to set a mastiff dog upon them.
But notwithstanding all their cruelty both against Friends that lived there,
though but three or four, and also strangers that came to visit them,
in a little time a meeting was settled, and several convinced,
for which the Lord shall have the praise.

In the year 1693,
Andrew Taylor and I travelled into the west and south parts of this nation;
and visiting Friends in Westmoreland, Lancashire, Cheshire, Herefordshire,
Gloucestershire, and so to Bristol,
had many good opportunities both among Friends and others.

After we were clear of Bristol, we visited Friends in Somersetshire, Dorcetshire,
Devonshire, Hampshire, Sussex and Kent, and so to London:
in most places there was an openness to hear the truth,
though an unwillingness to bear the cross.
And after we had stayed two weeks in London, to our great satisfaction,
we set forward to Barnet, and had a meeting;
and visited Friends`' meetings all along by Northampton, Nottingham, Leeds,
and so to Cumberland to our own dwellings, where we found all well.

Living not far from Scotland, I had a desire to visit some parts of that nation;
and having had meetings near the border, and one at Gretna, in Scotland,
people of several sorts were deeply affected with the testimony of truth;
afterwards with some other Friends, I appointed a meeting at Broomholm,
where we had liberty granted by the owner of the ground.
But the priests perceiving it,
by their threatenings affrighted the man so that he would not let us meet upon his ground.
We being stopped on the highway on Tarras-side, sat down together.
Now the elders, with others, being commanded to come out of several parishes,
used violence to drive us away, but could not prevail;
and after some time they went away a mile or more to Canonsby kirk,
(so called) and by the consent of the priest came with officers and rude shabby lads,
and youths void of understanding, and laid violent hands upon Friends,
and men and boys without either fear or wit, beat and abused Friends,
and broke John Bowsted`'s head till the blood ran down.
They that commanded this rabble were the elders and other men of note;
but a brave warfare it was, and Friends kept their places, old and young,
and the meeting continued near three hours,
where several Friends declared the testimony of truth amongst them.
And the Presbyterian spirit and the cruelty of it, was both seen and judged by many.
Friends returned home with peace and satisfaction.

Since that time, several things fell out that are remarkable;
particularly an accident that happened not long after, on a first-day,
when people had been at their worship at the aforesaid kirk of Canonsby.
In their return, going over the river Esk, near the kirk, in a boat,
being thirty-five persons or thereabouts, it suddenly sunk down into the water,
and twenty-eight were drowned, though not far from the land.
Though the same boat, as it was reported,
had carried over fifty-five at a time or thereabouts; and there being no apparent danger,
made the thing more remarkable.
As Friends`' care continued in having meetings in fresh places,
so at times many came to the meeting-house at Sikcside,
to hear the testimony of truth declared, and their expectations were often answered:
for when travelling Friends came into the county, they often visited us on first-days;
and they who came to hear, generally went away well satisfied.

When divers of our ancient Friends were removed by death,
and others disabled by old age and weakness of body,
it became more my concern to be engaged in the management
of the affairs of truth in our own county,
and to visit neighboring counties, and also the Yearly Meetings at London;
and to have meetings in fresh places both in our own country and in the borders of Scotland;
where we met with hard usage time after time, to their shame.

In the year 1698, towards the latter end of the ninth month, +++[+++old style,]
my wife and I went to visit Friends in Scotland,
and the harvest being backward that year in divers places as we travelled,
until we came to Aberdeen, people were but reaping their corn;
and a storm of snow having fallen and lain upon it for a month before it was reaped,
people made fires in the fields, it was so cold; which made both corn and fodder scarce.
The poor people looked like death, some died in the highways,
and more were supposed to die from the corn being unwholesome, than for want of bread.
As there had been more years than one that corn had been dear,
and many poor people were like to lose hope of having plenty again,
my wife in her testimony in a meeting at Kinmuck, beyond Aberdeen, had it to say,
"`There should be plenty of bread again,`" which being attended with the life of truth.
Friends that were but weak and poor believed, and seemed mightily to rejoice.
When we had visited all tire meetings there,
and been kindly received by Friends and many others,
we returned home and found our family well.

The next Yearly Meeting I went to London, and gave Friends an account;
and as the brethren`'s care had been that Friends in that country should not suffer want,
their care increased until plenty came.
About this time I wrote the following epistle to Friends.

An Epistle of love and advice to the people of the Lord everywhere.

Dear Friends,

Who are broken off from the wild olive, and grafted into the heavenly vine,
unto you my love and life flow with an earnest travail upon my spirit,
that as ye have known the watering showers of the Lord`'s heavenly rain to fall upon you,
you may not only bud and blossom,
but bring forth much fruit to the praise and glory of your heavenly Father;
to whom be dominion and honor forever and ever!

And now, dear Friends, who in measure have escaped the pollutions of this world,
and in all your sojourning in the way to Zion,
have had a godly care upon your minds to cease doing evil,
that ye may know a learning to do well; this is what I would remind you of;
rest not satisfied in that ye are come by the teaching of God`'s grace to eschew evil,
but also that ye may be found doing good;
knowing that it is the fruitless trees that cumber the ground.
It is high time for all to awake to righteousness:
for many are called to awake from unrighteousness, which is well so far;
but what will this avail, if fruits of righteousness be not brought forth?
For, as it is written,
the axe is laid to the root of the tree that the tree that
brings not forth good fruit may be hewn down,
and cast into the fire.
Therefore it is greatly needful to abide in the vine into which ye are already grafted,
that ye may be fruitful trees like Joseph of old, whose branches spread over the wall.

Friends, let none sit down at ease in the way to Zion, like some of old, who began well,
and ran well for a time, and sat down short of the true rest:
or like the young man that came unto Christ Jesus,
who had kept the commandments from his youth, yet wanted one thing;
and not giving up to follow the Lord fully,
sat down short of laying up heavenly treasure.
Therefore let all follow the Lord fully, who is the Captain of our salvation,
the great bishop and shepherd of the soul, who leads his sheep into green pastures,
feeds his flocks as by the still waters, and gives unto his own eternal life.

Let every one`'s eye be single unto the Lord,
that the whole body may be full of light Such it
is whose understandings the Lord doth open:
they see their duty unto God, and their duty one unto another.

It is therefore time for all that profess the true and living
faith that purifies the heart and works by love,
to come forth and show them selves, and walk in the light of the new Jerusalem,
where precedent is going before precept, example before doctrine,
and actions and doings before words and testimonies;
and on this wise the Lord is greatly at work in the hearts of his people,
to make them examples to others in the way to Zion,
where the saints`' solemnity is met with.

Dear Friends, who have given up yourselves to follow the Lamb in the way of regeneration,
and in some measure have known your garments washed; ye are to hold on your way,
for the mark is before: such the Lord is drawing near unto,
teaching them to lay up heavenly treasure.
It is the Lord that teaches his people to profit,
and such come to see in his light which makes manifest the will and mind of God to mankind,
that it is not enough to glorify God in your bodies and spirits, which are the Lord`'s;
but we are to serve the Lord with what we may receive from his bountiful hand,
of his outward mercies, of which many are made large stewards.
Remember the prayers and alms of Cornelius were accepted,
and ascended up for a memorial before the Lord,
to his great comfort and future happiness, and drew down a blessing upon his household.
Seeing that to do good and to communicate, is such a needful duty,
there is surely need to charge them who are rich in this world,
not to trust in uncertain riches but to trust in the living God,
who will call all men to an account of their stewardship one day;
for what we enjoy is the Lord`'s: therefore,
all that would be clear in the day of their account,
must wait for the Lord`'s ordering hand to be near them, who opened the heart of Lydia;
and her service was to invite the Lord`'s people into her house;
which being done in a right mind, brings a blessing; and such lose not their reward.

And as the good reward attends the good work, it hath been much upon my mind of late,
to remind the Lord`'s people to do good unto all,
but more especially to the household of faith;
and that all such who may have much of the outward mammon committed to their trust,
be not short of feeding the hungry, clothing the naked, entertaining strangers,
visiting the sick, and them that are in prison, which must needs be a necessary duty,
seeing the Lord takes it as done unto himself.
And, that none of the Lord`'s people may be found wanting in the day of their account,
let it be the care of all who expect a good reward from the hand of the Lord,
to sow plentifully that they may reap plentifully; for they that sow sparingly,
saith the apostle, shall reap sparingly;
and the time draweth near that every one must receive a reward according to his works.
What will it profit any then, if they had gained the whole world, and lost their own soul?
For, as it is written, "`When the Son of Man shall come in his glory,
and all the holy angels with him, then shall he sit upon the throne of his glory.
And before him shall be gathered all nations;
and he shall separate them one from another,
as a shepherd divideth his sheep from the goats:
and he shall set the sheep on his right hand, but the goats on the left.
Then shall the King say unto them on his right hand.
Come, ye blessed of my Father,
inherit the kingdom prepared for you from the foundation of the world.
For I was an hungered, and ye gave me meat: I was thirsty, and ye gave me drink:
I was a stranger, and ye took me in: naked, and ye clothed me: I was sick,
and ye visited me: I was in prison, and ye came unto me.
Then shall the righteous answer him, saying, Lord, when saw we thee an hungered,
and fed thee?
or thirsty, and gave thee drink?
When saw we thee a stranger, and took thee in?
or naked, and clothed thee?
Or when saw we thee sick, or in prison, and came unto thee?
And the King shall answer, and say unto them.
Verily, I say unto you,
inasmuch as ye have done it unto one of the least of these my brethren,
ye have done it unto me.
Then shall he also say to them on the left hand.
Depart from me, ye cursed, into everlasting fire, prepared for the devil and his angels.
For I was an hungered, and ye gave me no meat: I was thirsty, and ye gave me no drink:
I was a stranger, and ye took me not in: naked, and ye clothed me not: sick,
and in prison, and ye visited me not.
Then shall they also answer him, saying, Lord, when saw we thee an hungered, or athirst,
or a stranger, or naked, or sick, or in prison, and did not minister unto thee?
Then shall he answer them, saying.
Verily I say unto you, inasmuch as ye did it not to one of the least of these,
ye did it not to me.
And these shall go away into everlasting punishment:
but the righteous into life eternal.`"
Oh! therefore, that none may rest satisfied in feeding, clothing,
and taking care of themselves n sickness,
+++[++++++[+++__ddelink__3548_1081059228]]etc. supposing to lay up durable riches,
and yet be unmindful of the poor, the widow, and the fatherless;
such will do well to make a narrow search,
and consider whether they are come to that religion which is pure and undefiled, that is,
to visit the fatherless and the widow, in their affliction;
and to keep unspotted of the world.

My dear Friends, in this time of ease and outward liberty,
which the Lord`'s faithful people greatly prize as
a mercy from the Lord`'s bountiful hand,
beware of the enemy of the soul,
that lies near to draw the minds of men and women to love the world,
and the things of this world; for whosoever loveth the world,
the love of the Father is not in him.
This unwearied adversary, whose transformings are many,
would come in under pretence of being a friend,
but in the light of the Lord is seen to be a devouring enemy;
not leading at first into open profaneness;
for many are dead to the gross evils that are in the world,
but rather into earthly-mindedness,
where little fruit is brought forth that is well pleasing unto the Lord;
and his end is to waste and destroy the heritage of the Lord.
Ought not all to pray, as their flight hath not been in the winter,
that it may not be on the Sabbath-day, for "`many are called,
but few are chosen`"? And the Lord in his mercy hath freed
us of many burdens which our elder brethren bore in the
heat of the day the memorial of whom is sweet to the living,
who gave their cheek to the smiter and their head to him that pulled off the hair.
That which they enjoyed today, they could not call their own tomorrow;
whose innocent sufferings made deep impressions upon many people,
and largely manifested their love to God and contempt of the world.
Many came to see that the Lord`'s people were diligent in laboring
in the outward creation that they might not be chargeable to others;
yet willing to give up their all, when called thereunto, to suffer for his name`'s sake.
Here their light shone to the admiration of many,
and great is become the gathering of the Lord`'s people,
who through many tribulations enter the kingdom,
and whose care is to lay up durable riches.

And now, let it be the care of such who may not be called to give up their all,
and manifest their love to God and contempt of the
world in suffering for his name`'s sake,
to be found doing the will of God, that there may be a delight in doing good,
and showing mercy; and that saying may be fulfilled, "`If thine enemy hunger, feed him;
if he thirst, give him drink;`" and then no doubt there will be a feeding one another;
and here it is made manifest, who they are that love enemies,
and such must of necessity love one another, as the Lord, for Christ`'s sake,
hath loved us.

And, dear Friends, our contempt of the world makes fruitful,
as we abide in the heavenly vine; and if there be such a true care as there ought to be,
to show forth the Lord`'s praise, who hath called us to glory and virtue,
he will open the eyes of many to see our love to God, and contempt of the world,
in this calm time, that many shall say,
These people are diligent and laborious in all their undertakings,
yet they exceed many of their equals in hospitality, in dispensing abroad,
and giving to the poor.
This being done in a right mind, always was and still is, a good work,
being done so as that they that did it, their end was not to be seen of men, for if so,
such have their reward;
but if done so that the left hand may not know what the right hand doeth, the Lord,
who sees in secret, will reward openly.

My dearly beloved Friends, whom the Lord hath given gif^s unto,
and who are become planters and waterers in his holy hand,
whose service is great in the church, to the bringing of many from far, unto the Lord,
may such do their day`'s work faithfully,
that there may not be a coming short of the crown in the end,
is the weighty concern that ought to remain upon their minds,
that there may be a readiness and willingness at all times,
to answer the Lord`'s requirings, and to show forth a good example unto all,
in keeping clear of those unnecessary entanglements of this life,
that may hurt their service in the church, remembering the saying of the apostle,
"`No man that warreth,
entangleth himself with the affairs of this life;`"
and "`We brought nothing into this world,
and it is certain we can carry nothing out; and having food and raiment,
let us be therewith content;`" signifying that the love of money is the root of all evil;
which while some coveted after, they have erred from the faith,
and pierced themselves through with many sorrows.
But thou, O man of God, flee these things, and follow after righteousness, godliness,
faith, love, patience, meekness charging him,
"`in the sight of God,`" and "`before Jesus Christ,`"
to "`keep this commandment without spot,
unrebukable, until the appearing of our Lord Jesus Christ; which in his time,
he shall show, who is the blessed and only Potentate,
the King of kings and Lord of lords, etc., to whom be honor and power everlasting.
Amen.`"

And, dear Friends, as there are diversities of gifts, by one and the same Spirit,
so the members of that holy body, of which Jesus Christ is the head,
have their several services in the body,
and many are become as pruners and diggers in the Lord`'s vineyard:
O that such may do their day`'s work faithfully!
For as I have already said, the old enemy is greatly at work,
to lead into earthly-mindedness,
and though little fruit is brought forth that is well-pleasing unto the Lord,
yet superfluous branches grow naturally, where there is a being often watered.
What must be done to the fruitless trees, that cumber the ground?
Shall they not be cut down?
It is written, "`A certain man had a fig-tree planted in his vineyard,
and he came and sought fruit thereon, and found none;
then said he to the dresser of his vineyard,
Behold these three years I come seeking fruit on this fig-tree, and find none;
cut it down, why cumbereth it the ground?
And he answered and said unto him.
Lord, let it alone this year also, till I shall dig about it, and dung it;
and if it bear fruit, well; and if not, then after that thou shalt cut it down.`"
So it appears the fruitless trees are not to be let alone to cumber the ground.

And therefore, men being compared unto trees,
what great need is there for all that profess the way and the truth of the Lord,
to be so fruitful, as that men may call them trees of righteousness;
and seeing the tree is known by the fruit,
that such fruit may be brought forth by the Lord`'s people everywhere,
as will demonstrate that they are branches of the heavenly vine.
The apostle Peter exhorts the believers,
who had escaped the corruption that is in the world, through lust;
"`And besides this,`" says he, "`giving all diligence, add to your faith, virtue;
and to virtue, knowledge; and to knowledge, temperance; and to temperance, patience;
and to patience, godliness; and to godliness, brotherly-kindness;
and to brotherly kindness, charity.`"
What is aimed at, in the whole matter herein contained,
is that all may be found in those things,
that make neither "`barren nor unfruitful in the knowledge of our Lord
Jesus Christ;`" "`but he that lacketh these things,`" saith the apostle,
"`is blind, and cannot see far off,
and hath forgotten that he was purged from his old sins.`"
I shall conclude with the saying of the apostle,
"`I will not be negligent to put you always in remembrance of these things,
though ye know them, and be established in the present truth: yea,
I think it meet as long as I live in this tabernacle, to stir you up,
by putting you in remembrance.`"

In a feeling of that divine sweetness, and ray of God`'s glory,
that covers the souls of the righteous,
do I unfeignedly salute all that are sojourning in the way of Zion,
sincerely desiring your happy end and safe arrival at that eternal rest,
where the righteous shall ever live,
to praise and magnify the worthy name of the Lord God, and the Lamb,
that sits upon the throne, forever and ever.
Amen.

By a lover of truth and righteousness,

Christopher Story.

Righead in Cumberland, the 5th of the 11th month, 1699.

The number of Friends increasing, many being convinced, and Friends children growing up,
our meeting-house at Sikeside was too little to contain us, and in the aforesaid year,
1699,
(it being about twenty-seven years since our meeting
was first settled,) we enlarged the meeting-house,
which it is supposed will contain about three hundred, and is generally well filled;
many of our children growing up in the truth,
and being zealous for the God of their fathers.
Thus hath the Lord increased our number, and as the harvest is great,
and the laborers but few, there is great need to pray the Lord of the harvest,
to send forth more laborers; who can do what seems good in his sight,
to whom be honor and praise forever.
