[short="The Testimony of Bridget Story"]
== The Testimony of Bridget Story, concerning her deceased husband, Christopher Story.

The Lord, who is the giver of all good gifts,
and from whom all our mercies and blessings proceed,
graciously favored me with the privilege of this my dear husband,
whose company and fellowship, whilst I enjoyed them, were esteemed by me,
as the greatest of temporal mercies.
The loss of such a worthy husband affects my heart with great sorrow;
but in consideration that my loss, though very great, is his unspeakable gain,
I am therefore made to bless the Lord, who gives and takes away at his pleasure.
We lived together in the married state upwards of fifty years,
in true love and sweet concord.
It pleased God, a few years after our being married,
to visit my dear husband with the day-spring from on high, and it had such good effect,
as to bring him under the just judgments of God for sin.
And notwithstanding his being religiously inclined from his youth,
yet when the Lord was pleased to open his understanding,
he saw his building must all be thrown down, being not upon the true foundation;
and being humbled before the Lord, he willingly bowed under the yoke of Christ,
and took up his daily cross, and thereby became a disciple and follower of him.
The Lord having prepared him for his service,
in his own time endued him with a gift of the ministry,
being one of the first that was raised up in that service in this part of the country;
and continuing in faithfulness both in doing and in suffering,
which soon fell to his lot, he became very serviceable amongst his brethren,
who were then but few in number in those parts.

The Lord was pleased to lay a concern upon him to
visit the churches in divers places in this nation,
also in Scotland and Ireland, several times.
And I doubt not but his labor of love was blessed,
he being endued with a gift of the ministry that was not only plain,
but powerful and edifying, and often fell upon the heritage of God,
as a sweet shower upon the tender grass,
whereby they were comforted and refreshed in the Lord.

His care was great over the churches of Christ,
that all might be preserved in true love and unity;
and the Lord was pleased to furnish him with an excellent
understanding in the affairs relating to the Discipline,
and the good order established therein.
He was very diligent and unwearied in attending such meetings;
and his blameless conversation, and the authority he was endued with,
gave him great room amongst his brethren, who much loved and honored him.
It is not within the reach of my capacity to set forth the worth of this my dear husband,
yet I thought it my duty to pay this tribute to his memory,
for he was not only an husband, but even as a nursing father to me,
and a tender and watchful father over our children.
The remembrance of the many sweet and comfortable times
I have enjoyed with him among the Lord`'s people,
gives me occasion to bless the Lord,
and also humbly to beg of him to raise up others in the room of him,
and of many more of our worthy ancients who are removed from us,
to stand as faithful testimony-bearers, for his name and truth upon the earth;
that the Lord`'s great work that he has begun may go on and prosper,
and many may be turned to him.
My dear husband was a pattern of humility and good
conduct in his family in the time of his health;
and exemplary in his last illness, patiently bearing his affliction.
His disease was not violent; but, of the nature of a consumption.

He continued to attend meetings very diligently, as long as natural strength admitted,
and many times appeared in testimony very sweetly and lively, though very weak in body.
He died the 6th day of the eleventh month, 1720,
and his remains were buried the 8th day of the same,
at Friends`' burying-place at Hetherside,
being accompanied thither by a very great number of Friends and others.

[.signed-section-signature]
Bridget Story.
