[#aaron, short="The Testimony of Aaron Atkinson"]
== The Testimony of Aaron Atkinson, concerning his beloved friend, Christopher Story.

My deceased friend was the instrument in the Lord`'s hand for my convincement.
In the year 1688, I went to an evening meeting, held at the house of Christopher Taylor,
at Hetherside, in the parish of Kirklinton, and county of Cumberland,
where he preached the everlasting Gospel in the demonstration
of the spirit and power of God;
at which time I was effectually convinced, and fully resolved never to depart from it.
The next morning this meek man of God came where I was, and set me on my way,
and tenderly dropped matter suitable to the condition I was then in,
to my comfort and encouragement.
He continued to be a father in Christ to me; and my spirit was subject to him,
as his son in the Lord.
I sincerely loved him, and preferred him in meetings of worship and business;
and I do not remember that I ever was in a meeting where his mouth wag opened,
but he added something to me.
After it pleased God to engage me in the ministry of the Gospel,
I several times travelled with this Friend, and he was a great help to me in my exercise;
I could freely lay both my strength and weakness open to him to judge of.
He was a good example in self-denial, humility, and temperance, a true Christian,
a qualified elder, and a gifted minister of Christ,
by whom God was pleased to edify his church.
He was a wise man, and understanding in things of this life also;
and was very serviceable among Friends in weighty matters.
I often with satisfaction beheld his innocency and patience,
and how forbearing he was in the time of provocation for the church`'s peace,
and careful when he spoke to matters not to give offence to his brethren.
He was so preserved in the peaceable spirit of Christ,
in the management of the affairs of the church,
that there was an ear open to hear him to his dying day.
And without doubt,
those that were joined with him in a concern for
Zion`'s prosperity and Jerusalem`'s welfare,
will feel the loss of him.
I visited him in the time of his illness, and found him well in the Lord,
and had true unity with him; and I am satisfied he is entered into everlasting rest.
The Lord who in love and mercy raised him up, and made him serviceable in his generation,
is able to bring up others in his stead to answer the same service,
to the honor and glory of his own name.

[.signed-section-signature]
Aaron Atkinson.

[.signed-section-context-close]
Leeds, the 21st of the 2d month, 1721.
